---
permalink: protect-scsql/concept_when_to_schedule_verification_jobs.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: 'Obwohl SnapCenter Backups unmittelbar nach der Erstellung überprüfen kann, kann dies die zum Abschließen des Backup-Auftrags erforderliche Zeit erheblich verlängern und ist ressourcenintensiv.  Daher ist es fast immer am besten, die Überprüfung in einem separaten Job für einen späteren Zeitpunkt einzuplanen.  Wenn Sie beispielsweise täglich um 17:00 Uhr eine Datenbank sichern, können Sie die Überprüfung eine Stunde später um 18:00 Uhr planen.' 
---
= Wann sollten Überprüfungsjobs geplant werden?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Obwohl SnapCenter Backups unmittelbar nach der Erstellung überprüfen kann, kann dies die zum Abschließen des Backup-Auftrags erforderliche Zeit erheblich verlängern und ist ressourcenintensiv.  Daher ist es fast immer am besten, die Überprüfung in einem separaten Job für einen späteren Zeitpunkt einzuplanen.  Wenn Sie beispielsweise täglich um 17:00 Uhr eine Datenbank sichern, können Sie die Überprüfung eine Stunde später um 18:00 Uhr planen.

Aus demselben Grund ist es normalerweise nicht notwendig, bei jeder Sicherung eine Sicherungsüberprüfung durchzuführen.  Um die Integrität der Sicherung sicherzustellen, reicht es normalerweise aus, in regelmäßigen, aber weniger häufigen Abständen eine Überprüfung durchzuführen.  Ein einzelner Überprüfungsauftrag kann mehrere Sicherungen gleichzeitig überprüfen.
