---
permalink: protect-scsql/concept_how_long_to_retain_transaction_log_backups_on_the_source_storage_system.html 
sidebar: sidebar 
keywords: retain transaction log backups 
summary: Das SnapCenter Plug-in für Microsoft SQL Server benötigt Transaktionsprotokollsicherungen, um aktuelle Wiederherstellungsvorgänge durchzuführen, die Ihre Datenbank auf einen Zeitpunkt zwischen zwei vollständigen Sicherungen wiederherstellen. 
---
= Wie lange sollen Transaktionsprotokollsicherungen auf dem Quellspeichersystem aufbewahrt werden?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SnapCenter Plug-in für Microsoft SQL Server benötigt Transaktionsprotokollsicherungen, um aktuelle Wiederherstellungsvorgänge durchzuführen, die Ihre Datenbank auf einen Zeitpunkt zwischen zwei vollständigen Sicherungen wiederherstellen.

Wenn Plug-in für SQL Server beispielsweise um 8:00 Uhr eine vollständige Sicherung und um 17:00 Uhr eine weitere vollständige Sicherung erstellt hat, kann es die neueste Transaktionsprotokollsicherung verwenden, um die Datenbank auf einen beliebigen Zeitpunkt zwischen 8:00 Uhr und 17:00 Uhr wiederherzustellen. Wenn keine Transaktionsprotokolle verfügbar sind, kann Plug-in für SQL Server nur zeitpunktbezogene Wiederherstellungsvorgänge durchführen, die eine Datenbank auf den Zeitpunkt wiederherstellen, zu dem Plug-in für SQL Server eine vollständige Sicherung abgeschlossen hat.

Normalerweise benötigen Sie aktuelle Wiederherstellungsvorgänge nur für ein oder zwei Tage.  Standardmäßig behält SnapCenter mindestens zwei Tage.
