---
permalink: protect-scsql/task_failback_from_scsql_secondary_storage_to_primary_storage.html 
sidebar: sidebar 
keywords: failback, snapcenter 
summary: Nachdem das SnapCenter -Plug-In für den primären SQL Server-Speicher wieder online ist, sollten Sie ein Failback auf den primären Speicher durchführen. 
---
= Failback vom SnapCenter Plug-in für den sekundären SQL Server-Speicher zum primären Speicher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem das SnapCenter -Plug-In für den primären SQL Server-Speicher wieder online ist, sollten Sie ein Failback auf den primären Speicher durchführen.

.Bevor Sie beginnen
* Versetzen Sie das SnapCenter -Plug-in für SQL Server auf der Seite „Verwaltete Hosts“ in den Wartungsmodus.
* Trennen Sie den sekundären Speicher vom Host und stellen Sie eine Verbindung vom primären Speicher her.
* Um ein Failback zum primären Speicher durchzuführen, stellen Sie sicher, dass die Beziehungsrichtung dieselbe bleibt wie vor dem Failover, indem Sie den umgekehrten Resynchronisierungsvorgang durchführen.
+
Um die Rollen des primären und sekundären Speichers nach dem umgekehrten Resynchronisierungsvorgang beizubehalten, führen Sie den umgekehrten Resynchronisierungsvorgang noch einmal durch.

+
Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_reverse_resynchronizing_snapmirror_relationships.html["Umgekehrte Neusynchronisierung von Spiegelbeziehungen"]

* Starten Sie den MSSQL-Serverdienst neu.
* Stellen Sie sicher, dass die SQL-Ressourcen wieder online sind.



NOTE: Während eines Failovers oder Failbacks des Plug-Ins wird der Gesamtstatus des Plug-Ins nicht sofort aktualisiert.  Der Gesamtstatus des Hosts und des Plug-Ins wird während des nachfolgenden Host-Aktualisierungsvorgangs aktualisiert.

.Schritte
. Navigieren Sie auf der Seite „Einstellungen“ zu *Einstellungen* > *Globale Einstellungen* > *Notfallwiederherstellung*.
. Deaktivieren Sie *Notfallwiederherstellung aktivieren*.
. Klicken Sie auf *Übernehmen*.
. Überprüfen Sie, ob der DR-Job aktiviert ist oder nicht, indem Sie auf *Überwachen* > *Jobs* klicken.


.Nach Abschluss
Sie können das SnapCenter -Plug-In für SQL Server-Sicherungen, die während des Failovers erstellt wurden, entweder über die Benutzeroberfläche oder das folgende Cmdlet löschen: `Remove-SmDRFailoverBackups`
