---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html 
sidebar: sidebar 
keywords:  
summary: Mit SnapCenter können Sie Klone aus einer Ressourcengruppe oder Datenbank erstellen.  Sie können entweder einen On-Demand-Klon durchführen oder wiederkehrende Klonvorgänge einer Ressourcengruppe oder Datenbank planen.  Wenn Sie regelmäßig ein Backup klonen, können Sie den Klon zum Entwickeln von Anwendungen, Auffüllen von Daten oder Wiederherstellen von Daten verwenden. 
---
= Klon-Lebenszyklus durchführen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit SnapCenter können Sie Klone aus einer Ressourcengruppe oder Datenbank erstellen.  Sie können entweder einen On-Demand-Klon durchführen oder wiederkehrende Klonvorgänge einer Ressourcengruppe oder Datenbank planen.  Wenn Sie regelmäßig ein Backup klonen, können Sie den Klon zum Entwickeln von Anwendungen, Auffüllen von Daten oder Wiederherstellen von Daten verwenden.

Mit SnapCenter können Sie mehrere Klonvorgänge planen, die gleichzeitig auf mehreren Servern ausgeführt werden.

.Bevor Sie beginnen
* Stellen Sie beim Klonen auf eine eigenständige Datenbankinstanz sicher, dass der Mount-Point-Pfad vorhanden ist und es sich um eine dedizierte Festplatte handelt.
* Stellen Sie beim Klonen auf eine Failoverclusterinstanz (FCI) sicher, dass die Bereitstellungspunkte vorhanden sind, es sich um eine gemeinsam genutzte Festplatte handelt und der Pfad und die FCI zur selben SQL-Ressourcengruppe gehören.
* Wenn sich die Quelldatenbank oder die Zielinstanz auf einem freigegebenen Clustervolume (CSV) befindet, befindet sich die geklonte Datenbank auf dem CSV.



NOTE: Stellen Sie bei virtuellen Umgebungen (VMDK/RDM) sicher, dass der Einhängepunkt eine dedizierte Festplatte ist.

.Informationen zu diesem Vorgang
* Der SCRIPTS_PATH wird mithilfe des Schlüssels „PredefinedWindowsScriptsDirectory“ definiert, der sich in der Datei „SMCoreServiceHost.exe.Config“ des Plug-In-Hosts befindet.
+
Bei Bedarf können Sie diesen Pfad ändern und den SMcore-Dienst neu starten.  Aus Sicherheitsgründen wird empfohlen, den Standardpfad zu verwenden.

+
Der Wert des Schlüssels kann von Swagger über die API angezeigt werden: API /4.7/configsettings

+
Sie können die GET-API verwenden, um den Wert des Schlüssels anzuzeigen.  SET-API wird nicht unterstützt.

* Die meisten Felder auf den Seiten des Assistenten „Lebenszyklus klonen“ sind selbsterklärend.  Die folgenden Informationen beschreiben Felder, für die Sie möglicherweise Anleitungen benötigen.
* Wenn Sie für ONTAP 9.12.1 und niedrigere Versionen eine Snapshot-Sperrzeit angeben, erben die aus den manipulationssicheren Snapshots erstellten Klone die Ablaufzeit von SnapLock . Der Speicheradministrator sollte die Klone nach Ablauf des SnapLock manuell bereinigen.


.Schritte
. Klicken Sie im linken Navigationsbereich auf *Ressourcen* und wählen Sie dann das entsprechende Plug-In aus der Liste aus.
. Wählen Sie auf der Seite „Ressourcen“ entweder „Datenbank“ oder „Ressourcengruppe“ aus der Liste „Anzeigen“ aus.
. Wählen Sie die Ressourcengruppe oder Datenbank aus und klicken Sie dann auf *Lebenszyklus klonen*.
. Führen Sie auf der Seite „Optionen“ die folgenden Aktionen aus:
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Name des Klonauftrags
 a| 
Geben Sie den Namen des Klon-Lebenszyklus-Jobs an, der bei der Überwachung und Änderung des Klon-Lebenszyklus-Jobs hilft.



 a| 
Server klonen
 a| 
Wählen Sie den Host aus, auf dem der Klon platziert werden soll.



 a| 
Instanz klonen
 a| 
Wählen Sie die Kloninstanz aus, auf die Sie die Datenbank klonen möchten.  Diese SQL-Instanz muss sich auf dem angegebenen Klonserver befinden.



 a| 
Klonsuffix
 a| 
Geben Sie ein Suffix ein, das an die Klondatenbank angehängt wird, um zu kennzeichnen, dass es sich um einen Klon handelt.  Jede SQL-Instanz, die zum Erstellen einer Klon-Ressourcengruppe verwendet wird, muss einen eindeutigen Datenbanknamen haben.  Wenn die Klon-Ressourcengruppe beispielsweise eine Quelldatenbank „`db1`“ aus einer SQL-Instanz „`inst1`“ enthält und „`db1`“ nach „`inst1`“ geklont wird, sollte der Name der Klon-Datenbank „`db1__clone`“ lauten.  „`__clone`“ ist ein obligatorisches benutzerdefiniertes Suffix, da die Datenbank auf dieselbe Instanz geklont wird.  Wenn „`db1`“ in die SQL-Instanz „`inst2`“ geklont wird, kann der Name der Klondatenbank „`db1`“ bleiben (das Suffix ist optional), da die Datenbank in eine andere Instanz geklont wird.



 a| 
Mount-Punkt automatisch zuweisen oder Volume-Mount-Punkt automatisch unter Pfad zuweisen
 a| 
Wählen Sie, ob automatisch ein Bereitstellungspunkt oder ein Volumebereitstellungspunkt unter einem Pfad zugewiesen werden soll.  Wenn Sie die automatische Zuweisung eines Volume-Mount-Punkts unter einem Pfad auswählen, können Sie ein bestimmtes Verzeichnis angeben.  Die Einhängepunkte werden in diesem Verzeichnis erstellt.  Bevor Sie diese Option wählen, müssen Sie sicherstellen, dass das Verzeichnis leer ist.  Wenn sich im Verzeichnis eine Datenbank befindet, befindet sich die Datenbank nach dem Mount-Vorgang in einem ungültigen Zustand.

|===
. Wählen Sie auf der Seite „Speicherort“ einen Speicherort aus, um einen Klon zu erstellen.
. Geben Sie auf der Skriptseite den Pfad und die Argumente des Präskripts oder Postskripts ein, das vor bzw. nach dem Klonvorgang ausgeführt werden soll.
+
Sie können beispielsweise ein Skript ausführen, um SNMP-Traps zu aktualisieren, Warnungen zu automatisieren, Protokolle zu senden usw.

+

NOTE: Der Prescripts- oder Postscripts-Pfad sollte keine Laufwerke oder Freigaben enthalten.  Der Pfad sollte relativ zum SCRIPTS_PATH sein.

+
Das Standard-Skript-Timeout beträgt 60 Sekunden.

. Führen Sie auf der Seite „Planen“ eine der folgenden Aktionen aus:
+
** Wählen Sie *Jetzt ausführen*, wenn Sie den Klonauftrag sofort ausführen möchten.
** Wählen Sie *Zeitplan konfigurieren*, wenn Sie festlegen möchten, wie häufig der Klonvorgang erfolgen soll, wann der Klonzeitplan beginnen soll, an welchem Tag der Klonvorgang erfolgen soll, wann der Zeitplan ablaufen soll und ob die Klone nach Ablauf des Zeitplans gelöscht werden müssen.


. Wählen Sie auf der Benachrichtigungsseite aus der Dropdownliste *E-Mail-Einstellungen* die Szenarien aus, in denen Sie die E-Mails senden möchten.
+
Sie müssen außerdem die E-Mail-Adressen des Absenders und des Empfängers sowie den Betreff der E-Mail angeben.  Wenn Sie den Bericht über den durchgeführten Klonvorgang anhängen möchten, wählen Sie *Jobbericht anhängen*.

+

NOTE: Für die E-Mail-Benachrichtigung müssen Sie die SMTP-Serverdetails entweder über die GUI oder den PowerShell-Befehl „Set-SmSmtpServer“ angegeben haben.

+
Für EMS finden Sie unter https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection.html["Verwalten der EMS-Datenerfassung"]

. Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig*.


Sie sollten den Klonvorgang mithilfe der Seite *Überwachen* > *Jobs* überwachen.
