---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter verwendet Anmeldeinformationen, um Benutzer für SnapCenter -Vorgänge zu authentifizieren.  Sie sollten Anmeldeinformationen für die Installation von SnapCenter -Plug-Ins und zusätzliche Anmeldeinformationen für die Durchführung von Datenschutzvorgängen auf Datenbanken oder Windows-Dateisystemen erstellen. 
---
= Einrichten der Anmeldeinformationen für das SnapCenter Plug-Ins-Paket für Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter verwendet Anmeldeinformationen, um Benutzer für SnapCenter -Vorgänge zu authentifizieren.  Sie sollten Anmeldeinformationen für die Installation von SnapCenter -Plug-Ins und zusätzliche Anmeldeinformationen für die Durchführung von Datenschutzvorgängen auf Datenbanken oder Windows-Dateisystemen erstellen.

.Bevor Sie beginnen
* Sie müssen Windows-Anmeldeinformationen einrichten, bevor Sie Plug-Ins installieren.
* Sie müssen die Anmeldeinformationen mit Administratorrechten einrichten, einschließlich Administratorrechten auf dem Remote-Host.
* SQL-Authentifizierung auf Windows-Hosts
+
Sie müssen nach der Installation der Plug-Ins SQL-Anmeldeinformationen einrichten.

+
Wenn Sie das SnapCenter -Plug-in für Microsoft SQL Server bereitstellen, müssen Sie nach der Installation der Plug-ins SQL-Anmeldeinformationen einrichten.  Richten Sie Anmeldeinformationen für einen Benutzer mit SQL Server-Sysadmin-Berechtigungen ein.

+
Die SQL-Authentifizierungsmethode authentifiziert sich gegenüber einer SQL Server-Instanz.  Dies bedeutet, dass in SnapCenter eine SQL Server-Instanz erkannt werden muss.  Daher müssen Sie vor dem Hinzufügen von SQL-Anmeldeinformationen einen Host hinzufügen, Plug-In-Pakete installieren und Ressourcen aktualisieren.  Sie benötigen eine SQL Server-Authentifizierung, um Vorgänge wie das Planen oder Ermitteln von Ressourcen auszuführen.



.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite „Einstellungen“ auf *Anmeldeinformationen*.
. Klicken Sie auf *Neu*.
. Geben Sie auf der Seite „Anmeldeinformationen“ die zum Konfigurieren der Anmeldeinformationen erforderlichen Informationen an:
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Anmeldeinformationsname
 a| 
Geben Sie einen Namen für die Anmeldeinformationen ein.



 a| 
Benutzername/Passwort
 a| 
Geben Sie den Benutzernamen und das Kennwort ein, die zur Authentifizierung verwendet werden sollen.

** Domänenadministrator
+
Geben Sie den Domänenadministrator auf dem System an, auf dem Sie das SnapCenter -Plug-In installieren. Gültige Formate für das Feld „Benutzername“ sind:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Lokaler Administrator (nur für Arbeitsgruppen)
+
Geben Sie für Systeme, die zu einer Arbeitsgruppe gehören, den integrierten lokalen Administrator auf dem System an, auf dem Sie das SnapCenter -Plug-In installieren. Sie können ein lokales Benutzerkonto angeben, das zur lokalen Administratorgruppe gehört, wenn das Benutzerkonto über erhöhte Berechtigungen verfügt oder die Benutzerzugriffssteuerung auf dem Hostsystem deaktiviert ist.  Das gültige Format für das Feld „Benutzername“ ist: `UserName`

+
Verwenden Sie in den Passwörtern keine doppelten Anführungszeichen (") oder Backticks (`).  Sie sollten die Zeichen „Kleiner als“ (<) und „Ausrufezeichen“ (!) nicht zusammen in Passwörtern verwenden.  Zum Beispiel kleiner als <!10, kleiner als 10 <!, Backtick `12.





 a| 
Authentifizierungsmodus
 a| 
Wählen Sie den Authentifizierungsmodus aus, den Sie verwenden möchten.  Wenn Sie den SQL-Authentifizierungsmodus auswählen, müssen Sie auch die SQL-Serverinstanz und den Host angeben, auf dem sich die SQL-Instanz befindet.

|===
. Klicken Sie auf *OK*.


Nachdem Sie die Anmeldeinformationen eingerichtet haben, möchten Sie möglicherweise die Anmeldeinformationsverwaltung einem Benutzer oder einer Benutzergruppe auf der Seite „Benutzer und Zugriff“ zuweisen.
