---
permalink: protect-sco/discover-oracle-database.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: So erkennt SnapCenter Oracle-Datenbanken. 
---
= So erkennt SnapCenter Oracle-Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ressourcen sind Oracle-Datenbanken auf dem Host, die von SnapCenter verwaltet werden.  Sie können diese Datenbanken zu Ressourcengruppen hinzufügen, um Datenschutzvorgänge durchzuführen, nachdem Sie die verfügbaren Datenbanken ermittelt haben.

In den folgenden Abschnitten wird der Prozess beschrieben, den SnapCenter zum Erkennen verschiedener Typen und Versionen von Oracle-Datenbanken verwendet.



== Für Oracle-Versionen 11__g__ bis 12__c__R1

.RAC-Datenbank
Die RAC-Datenbanken werden nur auf der Grundlage von /etc/oratab`-Einträgen erkannt.  Sie sollten die Datenbankeinträge in der Datei /etc/oratab haben.

.Eigenständig
Die eigenständigen Datenbanken werden nur auf der Grundlage von /etc/oratab-Einträgen erkannt.

.ASM
Der ASM-Instanzeintrag sollte in der Datei /etc/oratab verfügbar sein.

.RAC Ein Knoten
Die RAC One Node-Datenbanken werden nur auf der Grundlage von /etc/oratab-Einträgen erkannt.  Die Datenbanken sollten sich entweder im Status „nomount“, „mount“ oder „open“ befinden.  Sie sollten die Datenbankeinträge in der Datei /etc/oratab haben.

Der Datenbankstatus von RAC One Node wird als umbenannt oder gelöscht markiert, wenn die Datenbank bereits erkannt wurde und Sicherungen mit der Datenbank verknüpft sind.

Bei einer Datenbankverlagerung sollten Sie folgende Schritte durchführen:

. Fügen Sie den verschobenen Datenbankeintrag manuell in die Datei /etc/oratab auf dem fehlgeschlagenen RAC-Knoten ein.
. Aktualisieren Sie die Ressourcen manuell.
. Wählen Sie auf der Ressourcenseite die RAC One Node-Datenbank aus und klicken Sie dann auf Datenbankeinstellungen.
. Konfigurieren Sie die Datenbank, um die bevorzugten Clusterknoten auf den RAC-Knoten festzulegen, der derzeit die Datenbank hostet.
. Führen Sie die SnapCenter -Vorgänge durch.
. Wenn Sie eine Datenbank von einem Knoten auf einen anderen Knoten verschoben haben und der oratab-Eintrag im vorherigen Knoten nicht gelöscht wurde, löschen Sie den oratab-Eintrag manuell, um zu vermeiden, dass dieselbe Datenbank zweimal angezeigt wird.




== Für Oracle-Versionen 12cR2 bis 18c, 19c oder 21c

.RAC-Datenbank
Die RAC-Datenbanken werden mit dem Befehl „srvctl config“ erkannt.  Sie sollten die Datenbankeinträge in der Datei /etc/oratab haben.

.Eigenständig
Die eigenständigen Datenbanken werden anhand der Einträge in der Datei /etc/oratab und der Ausgabe des Befehls „srvctl config“ erkannt.

.ASM
Der ASM-Instanzeintrag muss nicht in der Datei /etc/oratab enthalten sein.

.RAC Ein Knoten
Die RAC One Node-Datenbanken werden nur mit dem Befehl „srvctl config“ erkannt.  Die Datenbanken sollten sich entweder im Status „nomount“, „mount“ oder „open“ befinden.  Der Datenbankstatus von RAC One Node wird als umbenannt oder gelöscht markiert, wenn die Datenbank bereits erkannt wurde und Sicherungen mit der Datenbank verknüpft sind.

Bei einer Verlagerung der Datenbank sollten Sie folgende Schritte durchführen: .  Aktualisieren Sie die Ressourcen manuell. .  Wählen Sie auf der Ressourcenseite die RAC One Node-Datenbank aus und klicken Sie dann auf Datenbankeinstellungen. .  Konfigurieren Sie die Datenbank, um die bevorzugten Clusterknoten auf den RAC-Knoten festzulegen, der derzeit die Datenbank hostet. .  Führen Sie die SnapCenter -Vorgänge durch.


NOTE: Wenn in der Datei /etc/oratab Oracle 12__c__R2- und 18__c__-Datenbankeinträge vorhanden sind und dieselbe Datenbank mit dem Befehl srvctl config registriert ist, entfernt SnapCenter die doppelten Datenbankeinträge.  Wenn veraltete Datenbankeinträge vorhanden sind, wird die Datenbank zwar erkannt, ist jedoch nicht erreichbar und hat den Status „Offline“.
