---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-clone.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, clone 
summary: SnapCenter ermöglicht Ihnen die Verwendung der vordefinierten Umgebungsvariablen, wenn Sie beim Klonen einer Datenbank das Prescript und Postscript ausführen. 
---
= Vordefinierte Umgebungsvariablen für klonspezifisches Prescript und Postscript
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter ermöglicht Ihnen die Verwendung der vordefinierten Umgebungsvariablen, wenn Sie beim Klonen einer Datenbank das Prescript und Postscript ausführen.

*Unterstützte vordefinierte Umgebungsvariablen zum Klonen einer Datenbank*

* *SC_ORIGINAL_SID* gibt die SID der Quelldatenbank an.
+
Dieser Parameter wird für Anwendungsvolumes ausgefüllt.

+
Beispiel: NFSB32

* *SC_ORIGINAL_HOST* gibt den Namen des Quellhosts an.
+
Dieser Parameter wird für Anwendungsvolumes ausgefüllt.

+
Beispiel: asmrac1.gdl.englab.netapp.com

* *SC_ORACLE_HOME* gibt den Pfad des Oracle-Home-Verzeichnisses der Zieldatenbank an.
+
Beispiel: /ora01/app/oracle/product/18.1.0/db_1

* *SC_BACKUP_NAME*“ gibt den Namen der Sicherung an.
+
Dieser Parameter wird für Anwendungsvolumes ausgefüllt.

+
Beispiele:

+
** Wenn die Datenbank nicht im ARCHIVELOG-Modus ausgeführt wird: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
** Wenn die Datenbank im ARCHIVELOG-Modus ausgeführt wird: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG:RG2_scspr2417819002_07-20-2021_12.16.48.9267_1,RG2_scspr2417819002_07-21-2021_12.16.48.9267_1,RG2_scspr2417819002_07-22-2021_12.16.48.9267_1


* *SC_AV_NAME* gibt die Namen der Anwendungsvolumes an.
+
Beispiel: AV1|AV2

* *SC_ORIGINAL_OS_USER* gibt den Betriebssystembesitzer der Quelldatenbank an.
+
Beispiel: Orakel

* *SC_ORIGINAL_OS_GROUP* gibt die Betriebssystemgruppe der Quelldatenbank an.
+
Beispiel: oinstall

* *SC_TARGET_SID*“ gibt die SID der geklonten Datenbank an.
+
Für den PDB-Klon-Workflow ist der Wert dieses Parameters nicht vordefiniert.

+
Dieser Parameter wird für Anwendungsvolumes ausgefüllt.

+
Beispiel: clonedb

* *SC_TARGET_HOST* gibt den Namen des Hosts an, auf dem die Datenbank geklont wird.
+
Dieser Parameter wird für Anwendungsvolumes ausgefüllt.

+
Beispiel: asmrac1.gdl.englab.netapp.com

* *SC_TARGET_OS_USER* gibt den Betriebssystembesitzer der geklonten Datenbank an.
+
Für den PDB-Klon-Workflow ist der Wert dieses Parameters nicht vordefiniert.

+
Beispiel: Orakel

* *SC_TARGET_OS_GROUP* gibt die Betriebssystemgruppe der geklonten Datenbank an.
+
Für den PDB-Klon-Workflow ist der Wert dieses Parameters nicht vordefiniert.

+
Beispiel: oinstall

* *SC_TARGET_DB_PORT* gibt den Datenbankport der geklonten Datenbank an.
+
Für den PDB-Klon-Workflow ist der Wert dieses Parameters nicht vordefiniert.

+
Beispiel: 1521



Informationen zu Trennzeichen finden Sie unterlink:../protect-sco/predefined-environment-variables-prescript-postscript-backup.html#supported-delimiters["Unterstützte Trennzeichen"^] .
