---
permalink: protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html 
sidebar: sidebar 
keywords: storage types, iSCSI, NFS, RDM, VMDK, NFS, LVM, ASM, SAN filesystem 
summary: SnapCenter unterstützt eine breite Palette von Speichertypen auf physischen und virtuellen Maschinen.  Sie müssen die Unterstützung für Ihren Speichertyp überprüfen, bevor Sie das SnapCenter Plug-ins-Paket für Linux oder das SnapCenter Plug-ins-Paket für AIX installieren. 
---
= Vom Plug-in für Oracle-Datenbank unterstützte Speichertypen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter unterstützt eine breite Palette von Speichertypen auf physischen und virtuellen Maschinen.  Sie müssen die Unterstützung für Ihren Speichertyp überprüfen, bevor Sie das SnapCenter Plug-ins-Paket für Linux oder das SnapCenter Plug-ins-Paket für AIX installieren.

SnapCenter unterstützt keine Speicherbereitstellung für Linux und AIX.



== Unter Linux unterstützte Speichertypen

In der folgenden Tabelle sind die unter Linux unterstützten Speichertypen aufgeführt.

|===
| Maschine | Speichertyp 


 a| 
Physischer Server
 a| 
* FC-verbundene LUNs
* Über iSCSI verbundene LUNs
* Über NFS verbundene Volumes
* NVMe-FC
* NVMe/TCP




 a| 
VMware ESXi
 a| 
* RDM-LUNs, die über einen FC oder iSCSI ESXi HBA verbunden sind. Das Scannen von Host-Bus-Adaptern (HBAs) kann lange dauern, da SnapCenter alle im Host vorhandenen Host-Bus-Adapter scannt.
+
Sie können die Datei *LinuxConfig.pm* unter _/opt/ NetApp/snapcenter/spl/plugins/scu/scucore/modules/SCU/Config_ bearbeiten, um den Wert des Parameters *SCSI_HOSTS_OPTIMIZED_RESCAN* auf 1 zu setzen und nur die HBAs erneut zu scannen, die in HBA_DRIVER_NAMES aufgeführt sind.

* iSCSI-LUNs, die vom iSCSI-Initiator direkt mit dem Gastsystem verbunden sind
* VMDKs auf NFS-Datenspeichern
* VMDKs auf VMFS, die über NVMe/TCP erstellt wurden
+

NOTE: RAC wird auf ESX 8.0U2 unterstützt, das die Unterstützung für gemeinsam genutzte VMDK bietet

* NFS-Volumes, die direkt mit dem Gastsystem verbunden sind
* vVol-Datenspeicher auf NFS und SAN
+
vVol-Datenspeicher können nur mit ONTAP Tools für VMware vSphere bereitgestellt werden.



|===


== Unter AIX unterstützte Speichertypen

In der folgenden Tabelle sind die unter AIX unterstützten Speichertypen aufgeführt.

|===
| Maschine | Speichertyp 


 a| 
Physischer Server
 a| 
* FC-verbundene und iSCSI-verbundene LUNs.
+
In einer SAN-Umgebung werden ASM-, LVM- und SAN-Dateisysteme unterstützt.

+

NOTE: NFS auf AIX und Dateisystem wird nicht unterstützt.

* Erweitertes Journaled File System (JFS2)
+
Unterstützt Inline-Protokollierung auf SAN-Dateisystemen und LVM-Layout.



|===
Der https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["NetApp Interoperabilitätsmatrix-Tool"] enthält die neuesten Informationen zu den unterstützten Versionen.
