---
permalink: protect-sco/supported_backup_configs.html 
sidebar: sidebar 
keywords: backup type, preferred nodes, catalog backups, schedules, backup name format, retention, verification 
summary: SnapCenter unterstützt die Sicherung verschiedener Oracle-Datenbankkonfigurationen. 
---
= Unterstützte Oracle-Datenbankkonfigurationen für Backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter unterstützt die Sicherung verschiedener Oracle-Datenbankkonfigurationen.

* Oracle Standalone
* Oracle Real Application Clusters (RAC)
* Oracle Standalone Legacy
* Oracle Standalone Container Database (CDB)
* Oracle Data Guard-Standby
+
Sie können nur Offline-Mount-Backups von Data Guard-Standbydatenbanken erstellen.  Offline-Shutdown-Backup, reine Archivprotokoll-Backup und vollständige Backups werden nicht unterstützt.

* Oracle Active Data Guard-Standby
+
Sie können nur Online-Backups von Active Data Guard-Standbydatenbanken erstellen.  Nur Archivprotokollsicherungen und vollständige Sicherungen werden nicht unterstützt.

+
Vor dem Erstellen einer Sicherung der Data Guard-Standby- oder Active Data Guard-Standby-Datenbank wird der verwaltete Wiederherstellungsprozess (MRP) gestoppt und nach der Erstellung der Sicherung wird MRP gestartet.

* Automatisches Speichermanagement (ASM)
+
** ASM Standalone und ASM RAC auf Virtual Machine Disk (VMDK)
+
Unter allen für Oracle-Datenbanken unterstützten Wiederherstellungsmethoden können Sie auf VMDK nur eine Connect-and-Copy-Wiederherstellung von ASM RAC-Datenbanken durchführen.

** ASM Standalone und ASM RAC auf Raw Device Mapping (RDM) + Sie können Sicherungs-, Wiederherstellungs- und Klonvorgänge für Oracle-Datenbanken auf ASM durchführen, mit oder ohne ASMLib.
** Oracle ASM-Filtertreiber (ASMFD)
+
PDB-Migrations- und PDB-Klonvorgänge werden nicht unterstützt.

** Oracle Flex ASM




Die neuesten Informationen zu unterstützten Oracle-Versionen finden Sie im https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["NetApp Interoperabilitätsmatrix-Tool"^] .
