---
permalink: protect-sco/task_configure_snapcenter_plug_in_loader_service.html 
sidebar: sidebar 
keywords: SPL, plug-in loader service 
summary: Der SnapCenter Plug-in Loader -Dienst lädt das Plug-in-Paket für Linux oder AIX, um mit dem SnapCenter Server zu interagieren.  Der SnapCenter Plug-in Loader -Dienst wird installiert, wenn Sie das SnapCenter Plug-ins-Paket für Linux oder das SnapCenter Plug-ins-Paket für AIX installieren. 
---
= Konfigurieren des SnapCenter Plug-in Loader -Dienstes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der SnapCenter Plug-in Loader -Dienst lädt das Plug-in-Paket für Linux oder AIX, um mit dem SnapCenter Server zu interagieren.  Der SnapCenter Plug-in Loader -Dienst wird installiert, wenn Sie das SnapCenter Plug-ins-Paket für Linux oder das SnapCenter Plug-ins-Paket für AIX installieren.

*Über diese Aufgabe*

Nach der Installation des SnapCenter Plug-ins-Pakets für Linux oder des SnapCenter Plug-ins-Pakets für AIX wird der SnapCenter Plug-in Loader -Dienst automatisch gestartet.  Wenn der SnapCenter Plug-in Loader -Dienst nicht automatisch gestartet wird, sollten Sie:

* Stellen Sie sicher, dass das Verzeichnis, in dem das Plug-In ausgeführt wird, nicht gelöscht wird
* Erhöhen Sie den der Java Virtual Machine zugewiesenen Speicherplatz


Die Datei spl.properties, die sich unter _/custom_location/ NetApp/snapcenter/spl/etc/_ befindet, enthält die folgenden Parameter.  Diesen Parametern sind Standardwerte zugewiesen.

|===
| Parametername | Beschreibung 


 a| 
LOG_LEVEL
 a| 
Zeigt die unterstützten Protokollebenen an.

Die möglichen Werte sind TRACE, DEBUG, INFO, WARN, ERROR und FATAL.



 a| 
SPL_PROTOCOL
 a| 
Zeigt das vom SnapCenter Plug-in Loader unterstützte Protokoll an.

Es wird nur das HTTPS-Protokoll unterstützt.  Sie können den Wert hinzufügen, wenn der Standardwert fehlt.



 a| 
SNAPCENTER_SERVER_PROTOKOLL
 a| 
Zeigt das vom SnapCenter Server unterstützte Protokoll an.

Es wird nur das HTTPS-Protokoll unterstützt.  Sie können den Wert hinzufügen, wenn der Standardwert fehlt.



 a| 
SKIP_JAVAHOME_UPDATE
 a| 
Standardmäßig erkennt der SPL-Dienst den Java-Pfad und aktualisiert den JAVA_HOME-Parameter.

Daher ist der Standardwert auf FALSE gesetzt.  Sie können es auf TRUE setzen, wenn Sie das Standardverhalten deaktivieren und den Java-Pfad manuell korrigieren möchten.



 a| 
SPL_KEYSTORE_PASS
 a| 
Zeigt das Passwort der Keystore-Datei an.

Sie können diesen Wert nur ändern, wenn Sie das Kennwort ändern oder eine neue Keystore-Datei erstellen.



 a| 
SPL_PORT
 a| 
Zeigt die Portnummer an, auf der der SnapCenter Plug-in Loader -Dienst ausgeführt wird.

Sie können den Wert hinzufügen, wenn der Standardwert fehlt.


NOTE: Sie sollten den Wert nach der Installation der Plug-Ins nicht mehr ändern.



 a| 
SNAPCENTER_SERVER_HOST
 a| 
Zeigt die IP-Adresse oder den Hostnamen des SnapCenter -Servers an.



 a| 
SPL_KEYSTORE_PATH
 a| 
Zeigt den absoluten Pfad der Keystore-Datei an.



 a| 
SNAPCENTER_SERVER_PORT
 a| 
Zeigt die Portnummer an, auf der der SnapCenter -Server ausgeführt wird.



 a| 
LOGS_MAX_COUNT
 a| 
Zeigt die Anzahl der Protokolldateien des SnapCenter Plug-in Loader an, die im Ordner _/custom_location/snapcenter/spl/logs_ gespeichert sind.

Der Standardwert ist auf 5000 eingestellt.  Wenn die Anzahl größer als der angegebene Wert ist, werden die letzten 5000 geänderten Dateien beibehalten.  Die Überprüfung der Anzahl der Dateien erfolgt automatisch alle 24 Stunden ab dem Start des SnapCenter Plug-in Loader -Dienstes.


NOTE: Wenn Sie die Datei „spl.properties“ manuell löschen, wird die Anzahl der beizubehaltenden Dateien auf 9999 festgelegt.



 a| 
JAVA_HOME
 a| 
Zeigt den absoluten Verzeichnispfad des JAVA_HOME an, der zum Starten des SPL-Dienstes verwendet wird.

Dieser Pfad wird während der Installation und beim Starten von SPL festgelegt.



 a| 
LOG_MAX_SIZE
 a| 
Zeigt die maximale Größe der Job-Protokolldatei an.

Sobald die maximale Größe erreicht ist, wird die Protokolldatei komprimiert und die Protokolle in die neue Datei dieses Auftrags geschrieben.



 a| 
Protokolle der letzten Tage aufbewahren
 a| 
Zeigt die Anzahl der Tage an, bis zu denen die Protokolle aufbewahrt werden.



 a| 
Zertifikatsvalidierung aktivieren
 a| 
Zeigt „true“ an, wenn die CA-Zertifikatvalidierung für den Host aktiviert ist.

Sie können diesen Parameter entweder durch Bearbeiten der spl.properties oder mithilfe der SnapCenter -GUI oder des Cmdlets aktivieren oder deaktivieren.

|===
Wenn einem dieser Parameter nicht der Standardwert zugewiesen ist oder Sie den Wert zuweisen oder ändern möchten, können Sie die Datei spl.properties ändern.  Sie können auch die Datei „spl.properties“ überprüfen und bearbeiten, um alle Probleme im Zusammenhang mit den den Parametern zugewiesenen Werten zu beheben.  Nachdem Sie die Datei spl.properties geändert haben, sollten Sie den SnapCenter Plug-in Loader -Dienst neu starten.

*Schritte*

. Führen Sie je nach Bedarf eine der folgenden Aktionen aus:
+
** Starten Sie den SnapCenter Plug-in Loader -Dienst:
+
*** Führen Sie als Root-Benutzer Folgendes aus: `/custom_location/NetApp/snapcenter/spl/bin/spl start`
*** Führen Sie als Nicht-Root-Benutzer Folgendes aus: `sudo /custom_location/NetApp/snapcenter/spl/bin/spl start`


** Stoppen Sie den SnapCenter Plug-in Loader -Dienst:
+
*** Führen Sie als Root-Benutzer Folgendes aus: `/custom_location/NetApp/snapcenter/spl/bin/spl stop`
*** Führen Sie als Nicht-Root-Benutzer Folgendes aus: `sudo /custom_location/NetApp/snapcenter/spl/bin/spl stop`
+

NOTE: Sie können die Option -force mit dem Stoppbefehl verwenden, um den SnapCenter Plug-in Loader -Dienst zwangsweise zu stoppen.  Allerdings sollten Sie dabei vorsichtig sein, da dadurch auch die bestehenden Vorgänge beendet werden.



** Starten Sie den SnapCenter Plug-in Loader -Dienst neu:
+
*** Führen Sie als Root-Benutzer Folgendes aus: `/custom_location/NetApp/snapcenter/spl/bin/spl restart`
*** Führen Sie als Nicht-Root-Benutzer Folgendes aus: `sudo /custom_location/NetApp/snapcenter/spl/bin/spl restart`


** Ermitteln Sie den Status des SnapCenter Plug-in Loader Dienstes:
+
*** Führen Sie als Root-Benutzer Folgendes aus: `/custom_location/NetApp/snapcenter/spl/bin/spl status`
*** Führen Sie als Nicht-Root-Benutzer Folgendes aus: `sudo /custom_location/NetApp/snapcenter/spl/bin/spl status`


** Suchen Sie die Änderung im SnapCenter Plug-in Loader -Dienst:
+
*** Führen Sie als Root-Benutzer Folgendes aus: `/custom_location/NetApp/snapcenter/spl/bin/spl change`
*** Führen Sie als Nicht-Root-Benutzer Folgendes aus: `sudo /custom_location/NetApp/snapcenter/spl/bin/spl change`





