---
permalink: protect-sce/reference_granular_recovery_of_mails_and_mailbox.html 
sidebar: sidebar 
keywords: SMBR, Single Mailbox recovery, Exchange database 
summary: 'Mit der Single Mailbox Recovery (SMBR)-Software können Sie E-Mails oder Postfächer anstelle der gesamten Exchange-Datenbank wiederherstellen.' 
---
= Granulare Wiederherstellung von E-Mails und Postfächern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit der Single Mailbox Recovery (SMBR)-Software können Sie E-Mails oder Postfächer anstelle der gesamten Exchange-Datenbank wiederherstellen.

Das Wiederherstellen einer kompletten Datenbank, nur um eine einzelne E-Mail wiederherzustellen, kostet viel Zeit und Ressourcen.  SMBR hilft bei der schnellen Wiederherstellung der E-Mails, indem es eine Klonkopie des Snapshots erstellt und dann Microsoft-APIs verwendet, um das Postfach in SMBR zu mounten.  Informationen zur Verwendung von SMBR finden Sie unter https://docs.netapp.com/p/snap/smbr/8.3/Administrative-Server-Administration-Guide.pdf["SMBR-Administrationshandbuch"^] .

Weitere Informationen zu SMBR finden Sie hier:

* https://kb.netapp.com/Legacy/SMBR/How_to_manually_restore_a_single_item_with_SMBR["So stellen Sie ein einzelnes Element manuell mit SMBR wieder her (gilt auch für Ontrack Power Control-Wiederherstellungen)"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Single_Mailbox_Recovery_(SMBR)/How_to_restore_from_secondary_storage_in_SMBR_with_SnapCenter["So stellen Sie mit SnapCenter vom sekundären Speicher in SMBR wieder her"^]
* https://www.youtube.com/watch?v=wMSo049rREY&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg&index=3["Wiederherstellen von Microsoft Exchange-E-Mails aus SnapVault mithilfe von SMBR"^]

