---
permalink: protect-sce/reference_exchange_database_and_backup_verification.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Exchange Server 
summary: Das SnapCenter -Plug-in für Microsoft Exchange Server bietet keine Sicherungsüberprüfung. Sie können jedoch das mit Exchange bereitgestellte Tool „Eseutil“ verwenden, um Exchange-Datenbanken und -Sicherungen zu überprüfen. 
---
= Exchange-Datenbank und Backup-Verifizierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SnapCenter -Plug-in für Microsoft Exchange Server bietet keine Sicherungsüberprüfung. Sie können jedoch das mit Exchange bereitgestellte Tool „Eseutil“ verwenden, um Exchange-Datenbanken und -Sicherungen zu überprüfen.

Das Microsoft Exchange Eseutil-Tool ist ein Befehlszeilenprogramm, das in Ihrem Exchange-Server enthalten ist.  Mit dem Dienstprogramm können Sie Konsistenzprüfungen durchführen, um die Integrität von Exchange-Datenbanken und -Sicherungen zu überprüfen.

|===


| *Best Practice:* Es ist nicht notwendig, Konsistenzprüfungen für Datenbanken durchzuführen, die Teil einer Database Availability Group (DAG)-Konfiguration mit mindestens zwei Replikaten sind. 
|===
Weitere Informationen finden Sie unter https://docs.microsoft.com/en-us/exchange/exchange-server?view=exchserver-2019["Microsoft Exchange Server-Dokumentation"^] .
