---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenter verwendet Anmeldeinformationen, um Benutzer für SnapCenter -Vorgänge zu authentifizieren.  Sie sollten Anmeldeinformationen für die Installation des Plug-In-Pakets und zusätzliche Anmeldeinformationen für die Durchführung von Datenschutzvorgängen an Datenbanken erstellen. 
---
= Einrichten der Anmeldeinformationen für das SnapCenter -Plug-in für Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter verwendet Anmeldeinformationen, um Benutzer für SnapCenter -Vorgänge zu authentifizieren.  Sie sollten Anmeldeinformationen für die Installation des Plug-In-Pakets und zusätzliche Anmeldeinformationen für die Durchführung von Datenschutzvorgängen an Datenbanken erstellen.

.Informationen zu diesem Vorgang
Sie müssen Anmeldeinformationen für die Installation von Plug-Ins auf Windows-Hosts einrichten.  Obwohl Sie Anmeldeinformationen für Windows erstellen können, nachdem Sie Hosts bereitgestellt und Plug-Ins installiert haben, empfiehlt es sich, die Anmeldeinformationen nach dem Hinzufügen von SVMs zu erstellen, bevor Sie Hosts bereitstellen und Plug-Ins installieren.

Richten Sie die Anmeldeinformationen mit Administratorrechten ein, einschließlich Administratorrechten auf dem Remote-Host.

Wenn Sie Anmeldeinformationen für einzelne Ressourcengruppen einrichten und der Benutzername nicht über vollständige Administratorrechte verfügt, müssen Sie dem Benutzernamen mindestens die Ressourcengruppen- und Sicherungsrechte zuweisen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite „Einstellungen“ auf *Anmeldeinformationen*.
. Klicken Sie auf *Neu*.
+
Das Fenster „Anmeldeinformationen“ wird angezeigt.

. Gehen Sie auf der Seite „Anmeldeinformationen“ wie folgt vor:
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Anmeldeinformationsname
 a| 
Geben Sie einen Namen für die Anmeldeinformationen ein.



 a| 
Benutzername
 a| 
Geben Sie den Benutzernamen ein, der für die Authentifizierung verwendet wird.

** Domänenadministrator oder ein beliebiges Mitglied der Administratorgruppe
+
Geben Sie den Domänenadministrator oder ein beliebiges Mitglied der Administratorgruppe auf dem System an, auf dem Sie das SnapCenter Plug-In installieren. Gültige Formate für das Feld „Benutzername“ sind:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Lokaler Administrator (nur für Arbeitsgruppen)
+
Geben Sie für Systeme, die zu einer Arbeitsgruppe gehören, den integrierten lokalen Administrator auf dem System an, auf dem Sie das SnapCenter -Plug-In installieren. Sie können ein lokales Benutzerkonto angeben, das zur lokalen Administratorgruppe gehört, wenn das Benutzerkonto über erhöhte Berechtigungen verfügt oder die Benutzerzugriffssteuerung auf dem Hostsystem deaktiviert ist.  Das gültige Format für das Feld „Benutzername“ ist: `UserName`





 a| 
Passwort
 a| 
Geben Sie das zur Authentifizierung verwendete Passwort ein.



 a| 
Authentifizierung
 a| 
Wählen Sie Windows als Authentifizierungsmodus.

|===
. Klicken Sie auf *OK*.

