---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Sie können eine Sicherungsrichtlinie für die Exchange-Ressourcen oder für die Ressourcengruppen erstellen, bevor Sie SnapCenter zum Sichern von Microsoft Exchange Server-Ressourcen verwenden, oder Sie können eine Sicherungsrichtlinie erstellen, wenn Sie eine Ressourcengruppe erstellen oder eine einzelne Ressource sichern. 
---
= Erstellen von Sicherungsrichtlinien für Exchange Server-Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Sicherungsrichtlinie für die Exchange-Ressourcen oder für die Ressourcengruppen erstellen, bevor Sie SnapCenter zum Sichern von Microsoft Exchange Server-Ressourcen verwenden, oder Sie können eine Sicherungsrichtlinie erstellen, wenn Sie eine Ressourcengruppe erstellen oder eine einzelne Ressource sichern.

.Bevor Sie beginnen
* Sie müssen Ihre Datenschutzstrategie definiert haben.
+
Einzelheiten finden Sie in den Informationen zum Definieren einer Datenschutzstrategie für Exchange-Datenbanken.

* Sie müssen sich auf den Datenschutz vorbereitet haben, indem Sie Aufgaben wie die Installation von SnapCenter, das Hinzufügen von Hosts, das Identifizieren von Ressourcen und das Erstellen von Speichersystemverbindungen abgeschlossen haben.
* Sie müssen die Exchange Server-Ressourcen aktualisiert (erkannt) haben.
* Wenn Sie Snapshots auf einen Spiegel oder Tresor replizieren, muss der SnapCenter Administrator Ihnen die virtuellen Speichermaschinen (SVMs) sowohl für die Quell- als auch für die Zielvolumes zugewiesen haben.
* Wenn Sie die PowerShell-Skripte in Prescripts und Postscripts ausführen möchten, sollten Sie den Wert des `usePowershellProcessforScripts` Parameter auf true im `web.config` Datei.
+
Der Standardwert ist „false“.

* Überprüfen Sie die spezifischen Voraussetzungen und Einschränkungen der SnapMirror Active Sync. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Objektlimits für SnapMirror Active Sync"] .


.Informationen zu diesem Vorgang
* Eine Sicherungsrichtlinie ist ein Satz von Regeln, der regelt, wie Sie Sicherungen verwalten und aufbewahren und wie häufig die Ressource oder Ressourcengruppe gesichert wird.  Darüber hinaus können Sie Skripteinstellungen festlegen.  Das Angeben von Optionen in einer Richtlinie spart Zeit, wenn Sie die Richtlinie für eine andere Ressourcengruppe wiederverwenden möchten.
* Die vollständige Aufbewahrung von Backups ist an eine bestimmte Richtlinie gebunden.  Eine Datenbank oder Ressource, die Richtlinie A mit einer vollständigen Sicherungsaufbewahrung von 4 verwendet, behält 4 vollständige Sicherungen bei und hat keine Auswirkungen auf Richtlinie B für dieselbe Datenbank oder Ressource, die möglicherweise eine Aufbewahrung von 3 hat, um 3 vollständige Sicherungen beizubehalten.
* Die Aufbewahrung von Protokollsicherungen ist richtlinienübergreifend wirksam und gilt für alle Protokollsicherungen einer Datenbank oder Ressource.  Wenn also eine vollständige Sicherung mit Richtlinie B durchgeführt wird, wirkt sich die Protokollaufbewahrungseinstellung auf Protokollsicherungen aus, die mit Richtlinie A auf derselben Datenbank oder Ressource erstellt wurden.  Ebenso wirkt sich die Protokollaufbewahrungseinstellung für Richtlinie A auf Protokollsicherungen aus, die von Richtlinie B in derselben Datenbank erstellt wurden.
* Der SCRIPTS_PATH wird mithilfe des Schlüssels „PredefinedWindowsScriptsDirectory“ definiert, der sich in der Datei „SMCoreServiceHost.exe.Config“ des Plug-In-Hosts befindet.
+
Bei Bedarf können Sie diesen Pfad ändern und den SMcore-Dienst neu starten.  Aus Sicherheitsgründen wird empfohlen, den Standardpfad zu verwenden.

+
Der Wert des Schlüssels kann von Swagger über die API angezeigt werden: API /4.7/configsettings

+
Sie können die GET-API verwenden, um den Wert des Schlüssels anzuzeigen.  SET-API wird nicht unterstützt.

+
|===


| *Best Practice:* Am besten konfigurieren Sie die sekundäre Aufbewahrungsrichtlinie basierend auf der Anzahl der vollständigen und Protokollsicherungen, die Sie insgesamt aufbewahren möchten.  Wenn Sie sekundäre Aufbewahrungsrichtlinien konfigurieren, bedenken Sie, dass bei Datenbanken und Protokollen, die sich auf unterschiedlichen Volumes befinden, jede Sicherung drei Snapshots haben kann, und dass bei Datenbanken und Protokollen, die sich auf demselben Volume befinden, jede Sicherung zwei Snapshots haben kann. 
|===
* SnapLock
+
** Wenn die Option „Sicherungskopien für eine bestimmte Anzahl von Tagen aufbewahren“ ausgewählt ist, muss die SnapLock -Aufbewahrungsdauer kleiner oder gleich der angegebenen Aufbewahrungsdauer in Tagen sein.
+
Durch die Angabe einer Snapshot-Sperrfrist wird das Löschen der Snapshots verhindert, bis die Aufbewahrungsfrist abgelaufen ist. Dies kann dazu führen, dass mehr Snapshots aufbewahrt werden als in der Richtlinie angegeben.

+
Bei ONTAP 9.12.1 und niedrigeren Versionen erben die aus den SnapLock Vault-Snapshots erstellten Klone die Ablaufzeit von SnapLock Vault. Der Speicheradministrator sollte die Klone nach Ablauf des SnapLock manuell bereinigen.





.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite „Einstellungen“ auf *Richtlinien*.
. Klicken Sie auf *Neu*.
. Geben Sie auf der Seite „Name“ den Richtliniennamen und die Details ein.
. Führen Sie auf der Seite „Sicherungstyp und Replikation“ die folgenden Schritte aus:
+
.. Wählen Sie den Sicherungstyp:
+
|===
| Wenn Sie wollen... | Machen Sie Folgendes... 


 a| 
Sichern Sie die Datenbankdateien und die erforderlichen Transaktionsprotokolle
 a| 
Wählen Sie *Vollständige Sicherung und Protokollsicherung*.

Datenbanken werden mit Protokollkürzung gesichert und alle Protokolle werden gesichert, einschließlich der gekürzten Protokolle.


NOTE: Dies ist der empfohlene Sicherungstyp.



 a| 
Sichern Sie die Datenbankdateien und die nicht festgeschriebenen Transaktionsprotokolle
 a| 
Wählen Sie *Vollständige Sicherung*.

Datenbanken werden mit Protokollkürzung gesichert, gekürzte Protokolle werden nicht gesichert.



 a| 
Sichern Sie alle Transaktionsprotokolle
 a| 
Wählen Sie *Protokollsicherung*.

Alle Transaktionsprotokolle auf dem aktiven Dateisystem werden gesichert und es erfolgt keine Protokollkürzung.

Auf derselben Festplatte wie das Live-Protokoll wird ein _scebackupinfo_-Verzeichnis erstellt.  Dieses Verzeichnis enthält den Zeiger auf die inkrementellen Änderungen für die Exchange-Datenbank und ist nicht gleichbedeutend mit den vollständigen Protokolldateien.



 a| 
Sichern Sie alle Datenbankdateien und Transaktionsprotokolle, ohne die Transaktionsprotokolldateien zu kürzen
 a| 
Wählen Sie *Backup kopieren*.

Alle Datenbanken und alle Protokolle werden gesichert und es erfolgt keine Protokollkürzung.  Normalerweise verwenden Sie diesen Sicherungstyp zum erneuten Seeding eines Replikats oder zum Testen oder Diagnostizieren eines Problems.

|===
+

NOTE: Sie sollten den für Protokollsicherungen erforderlichen Speicherplatz auf Grundlage der vollständigen Sicherungsaufbewahrung und nicht auf Grundlage der minutengenauen (UTM) Aufbewahrung definieren.

+

NOTE: Erstellen Sie beim Umgang mit Exchange-Volumes (LUNs) separate Tresorrichtlinien für Protokolle und Datenbanken und legen Sie die Aufbewahrungsdauer (Keep) für die Protokollrichtlinie für jedes Label auf die doppelte Zahl fest wie für die Datenbankrichtlinie, wobei Sie dieselben Labels verwenden.  Weitere Informationen finden Sie unter https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_for_Exchange_Backups_only_keep_half_the_Snapshots_on_the_Vault_destination_log_volume["SnapCenter für Exchange-Backups speichert nur die Hälfte der Snapshots auf dem Vault-Zielprotokollvolume"^]

.. Wählen Sie im Abschnitt „Einstellungen der Datenbankverfügbarkeitsgruppe“ eine Aktion aus:
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Sichern aktiver Kopien
 a| 
Wählen Sie diese Option, um nur die aktiven Kopien der ausgewählten Datenbank zu sichern.

Bei Datenbankverfügbarkeitsgruppen (DAGs) sichert diese Option nur aktive Kopien aller Datenbanken in der DAG.

Passive Kopien werden nicht gesichert.



 a| 
Sicherungskopien auf Servern, die bei der Erstellung des Sicherungsauftrags ausgewählt werden sollen
 a| 
Wählen Sie diese Option, um alle Kopien der Datenbanken auf den ausgewählten Servern (aktiv und passiv) zu sichern.

Bei DAGs sichert diese Option sowohl aktive als auch passive Kopien aller Datenbanken auf den ausgewählten Servern.

|===
+

NOTE: In Clusterkonfigurationen werden die Sicherungen gemäß den in der Richtlinie festgelegten Aufbewahrungseinstellungen auf jedem Knoten des Clusters aufbewahrt.  Wenn sich der Besitzerknoten des Clusters ändert, bleiben die Sicherungen des vorherigen Besitzerknotens erhalten.  Die Aufbewahrung gilt nur auf Knotenebene.

.. Wählen Sie im Abschnitt „Häufigkeit planen“ einen oder mehrere der Häufigkeitstypen aus: *Auf Anfrage*, *Stündlich*, *Täglich*, *Wöchentlich* und *Monatlich*.
+

NOTE: Sie können den Zeitplan (Startdatum, Enddatum) für Sicherungsvorgänge beim Erstellen einer Ressourcengruppe angeben.  Auf diese Weise können Sie Ressourcengruppen erstellen, die dieselbe Richtlinie und Sicherungshäufigkeit verwenden, aber jeder Richtlinie unterschiedliche Sicherungspläne zuweisen.

+

NOTE: Wenn Sie 2:00 Uhr morgens geplant haben, wird der Zeitplan während der Sommerzeit (DST) nicht ausgelöst.

.. Wählen Sie die Richtlinienbezeichnung aus.
+

NOTE: Sie können primären Snapshots SnapMirror Labels für die Remote-Replikation zuweisen, sodass die primären Snapshots den Snapshot-Replikationsvorgang von SnapCenter auf sekundäre ONTAP -Systeme auslagern können. Dies kann erfolgen, ohne die Option SnapMirror oder SnapVault auf der Richtlinienseite zu aktivieren.

.. Wählen Sie im Abschnitt „Sekundäre Replikationsoptionen auswählen“ eine oder beide der folgenden sekundären Replikationsoptionen aus:
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Aktualisieren Sie SnapMirror nach dem Erstellen eines lokalen Snapshots
 a| 
Wählen Sie diese Option, um Spiegelkopien von Sicherungssätzen auf einem anderen Volume (SnapMirror) aufzubewahren.

Während der sekundären Replikation lädt die Ablaufzeit des SnapLock die Ablaufzeit des primären SnapLock .

Diese Option sollte für die aktive Synchronisierung von SnapMirror aktiviert werden.


IMPORTANT: Die Nur-Primär-Richtlinie kann nicht verwendet werden, wenn SnapMirror Active Sync für Exchange ONTAP -Volumes eingerichtet ist.  SnapCenter lässt dies nicht zu.  Sie sollten die Option „Spiegeln“ aktivieren.

Durch Klicken auf die Schaltfläche *Aktualisieren* auf der Seite „Topologie“ werden die Ablaufzeiten des sekundären und primären SnapLock aktualisiert, die von ONTAP abgerufen werden.

Sehen link:../protect-sce/task_view_exchange_backups_in_the_topology_page.html["Anzeigen von Exchange-Sicherungen auf der Seite „Topologie“"] .



 a| 
Aktualisieren Sie SnapVault nach dem Erstellen eines lokalen Snapshots
 a| 
Wählen Sie diese Option, um eine Backup-Replikation von Festplatte zu Festplatte durchzuführen.



 a| 
Fehleranzahl der Wiederholungsversuche
 a| 
Geben Sie die Anzahl der Replikationsversuche ein, die durchgeführt werden sollen, bevor der Prozess angehalten wird.

|===
+

NOTE: Sie sollten die SnapMirror Aufbewahrungsrichtlinie in ONTAP für den sekundären Speicher konfigurieren, um zu vermeiden, dass das maximale Limit für Snapshots auf dem sekundären Speicher erreicht wird.



. Konfigurieren Sie auf der Seite „Aufbewahrung“ die Aufbewahrungseinstellungen.
+
Die angezeigten Optionen hängen vom Sicherungstyp und der Häufigkeit ab, die Sie zuvor ausgewählt haben.

+

NOTE: Der maximale Aufbewahrungswert beträgt 1018. Sicherungen schlagen fehl, wenn die Aufbewahrung auf einen höheren Wert eingestellt ist, als von der zugrunde liegenden ONTAP Version unterstützt wird.

+

IMPORTANT: Sie müssen die Aufbewahrungsanzahl auf 2 oder höher einstellen, wenn Sie die SnapVault -Replikation aktivieren möchten.  Wenn Sie die Aufbewahrungsanzahl auf 1 setzen, schlägt der Aufbewahrungsvorgang möglicherweise fehl, da der erste Snapshot der Referenz-Snapshot für die SnapVault -Beziehung ist, bis ein neuerer Snapshot auf das Ziel repliziert wird.

+
.. Wählen Sie im Abschnitt „Aufbewahrungseinstellungen für Protokollsicherungen“ eine der folgenden Optionen aus:
+
|===
| Wenn Sie wollen... | Machen Sie Folgendes... 


 a| 
Behalten Sie nur eine bestimmte Anzahl von Protokollsicherungen
 a| 
Wählen Sie *Anzahl der vollständigen Sicherungen, für die Protokolle aufbewahrt werden* und geben Sie die Anzahl der vollständigen Sicherungen an, für die Sie eine minutengenaue Wiederherstellung wünschen.

Die minutengenaue Aufbewahrung (UTM) gilt für Protokollsicherungen, die über eine vollständige oder Protokollsicherung erstellt wurden.  Wenn beispielsweise die UTM-Aufbewahrungseinstellungen so konfiguriert sind, dass die Protokollsicherungen der letzten 5 vollständigen Sicherungen aufbewahrt werden, werden die Protokollsicherungen der letzten 5 vollständigen Sicherungen aufbewahrt.

Die im Rahmen von Voll- und Log-Backups erstellten Log-Ordner werden im Rahmen von UTM automatisch gelöscht.  Sie können die Protokollordner nicht manuell löschen.  Wenn beispielsweise die Aufbewahrungseinstellung für die vollständige oder vollständige und Protokollsicherung auf 1 Monat und die UTM-Aufbewahrung auf 10 Tage eingestellt ist, wird der im Rahmen dieser Sicherungen erstellte Protokollordner gemäß UTM gelöscht.  Infolgedessen sind nur 10-Tage-Protokollordner vorhanden und alle anderen Sicherungen sind für die Wiederherstellung zu einem bestimmten Zeitpunkt markiert.

Sie können den UTM-Aufbewahrungswert auf 0 setzen, wenn Sie keine minutengenaue Wiederherstellung durchführen möchten.  Dadurch wird die Wiederherstellung zu einem bestimmten Zeitpunkt ermöglicht.

*Best Practice:* Es ist am besten, wenn die Einstellung der Einstellung für „Gesamtanzahl der Snapshots (vollständige Sicherungen)“ im Abschnitt „Einstellungen für die Aufbewahrung vollständiger Sicherungen“ entspricht.  Dadurch wird sichergestellt, dass die Protokolldateien für jede vollständige Sicherung erhalten bleiben.



 a| 
Bewahren Sie die Sicherungskopien für eine bestimmte Anzahl von Tagen auf
 a| 
Wählen Sie die Option *Protokollsicherungen bis zuletzt aufbewahren* und geben Sie die Anzahl der Tage an, für die die Protokollsicherungskopien aufbewahrt werden sollen.

Die Protokollsicherungen werden bis zur Anzahl der Tage der vollständigen Sicherungen aufbewahrt.



 a| 
Snapshot-Sperrzeitraum
 a| 
Wählen Sie *Sperrzeitraum für Snapshot-Kopie* und wählen Sie Tage, Monate oder Jahre aus.

Die Aufbewahrungsdauer von SnapLock sollte weniger als 100 Jahre betragen.

|===
+
Wenn Sie als Sicherungstyp *Protokollsicherung* ausgewählt haben, werden Protokollsicherungen als Teil der aktuellen Aufbewahrungseinstellungen für vollständige Sicherungen aufbewahrt.

.. Wählen Sie im Abschnitt „Aufbewahrungseinstellungen für vollständige Sicherungen“ eine der folgenden Optionen für On-Demand-Sicherungen und dann eine für vollständige Sicherungen aus:
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Behalten Sie nur eine bestimmte Anzahl von Snapshots
 a| 
Wenn Sie die Anzahl der aufzubewahrenden Vollsicherungen angeben möchten, wählen Sie die Option *Gesamtzahl der aufzubewahrenden Snapshot-Kopien* und geben Sie die Anzahl der aufzubewahrenden Snapshots (Vollsicherungen) an.

Wenn die Anzahl der vollständigen Sicherungen die angegebene Zahl überschreitet, werden die vollständigen Sicherungen, die die angegebene Zahl überschreiten, gelöscht, wobei die ältesten Kopien zuerst gelöscht werden.



 a| 
Vollständige Backups für eine bestimmte Anzahl von Tagen aufbewahren
 a| 
Wählen Sie die Option *Snapshot-Kopien aufbewahren für* und geben Sie die Anzahl der Tage an, die Snapshots (vollständige Backups) aufbewahrt werden sollen.



 a| 
Sperrzeitraum für primäre Snapshots
 a| 
Wählen Sie *Sperrzeitraum für primäre Snapshot-Kopie* und wählen Sie Tage, Monate oder Jahre aus.

Die Aufbewahrungsdauer von SnapLock sollte weniger als 100 Jahre betragen.



 a| 
Sperrzeitraum für sekundäre Snapshots
 a| 
Wählen Sie *Sperrzeitraum für sekundäre Snapshot-Kopie* und wählen Sie Tage, Monate oder Jahre aus.

|===
+
Wenn Sie auf einem Host in einer DAG-Konfiguration eine Datenbank mit nur Protokollsicherungen und ohne vollständige Sicherungen haben, werden die Protokollsicherungen auf folgende Weise aufbewahrt:

+
*** Standardmäßig sucht SnapCenter die älteste vollständige Sicherung für diese Datenbank auf allen anderen Hosts im DAG und löscht alle Protokollsicherungen auf diesem Host, die vor der vollständigen Sicherung erstellt wurden.
*** Sie können das oben genannte Standardaufbewahrungsverhalten für eine Datenbank auf einem Host in einem DAG mit ausschließlich Protokollsicherungen überschreiben, indem Sie den Schlüssel *MaxLogBackupOnlyCountWithoutFullBackup* in der Datei _C:\Program Files\ NetApp\ SnapCenter WebApp\web.config_ hinzufügen.
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
Im Beispiel bedeutet der Wert 10, dass Sie bis zu 10 Protokollsicherungen auf dem Host aufbewahren.





. Geben Sie auf der Seite „Skript“ den Pfad und die Argumente des Präskripts oder Postskripts ein, das vor bzw. nach dem Sicherungsvorgang ausgeführt werden soll.
+
** Zu den Prescript-Sicherungsargumenten gehören „`$Database`“ und „`$ServerInstance`“.
** Zu den Postscript-Sicherungsargumenten gehören „`$Database`“, „`$ServerInstance`“, „`$BackupName`“, „`$LogDirectory`“ und „`$LogSnapshot`“.
+
Sie können ein Skript ausführen, um SNMP-Traps zu aktualisieren, Warnungen zu automatisieren, Protokolle zu senden usw.

+

NOTE: Der Prescripts- oder Postscripts-Pfad sollte keine Laufwerke oder Freigaben enthalten.  Der Pfad sollte relativ zum SCRIPTS_PATH sein.



. Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig*.

