---
permalink: protect-scw/concept_snapcenter_plug_in_for_windows_features.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Das Plug-in für Windows lässt sich in die NetApp Snapshot-Technologie auf dem Speichersystem integrieren.  Um mit dem Plug-in für Windows zu arbeiten, verwenden Sie die SnapCenter -Schnittstelle. 
---
= Funktionen des SnapCenter -Plug-ins für Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Plug-in für Windows lässt sich in die NetApp Snapshot-Technologie auf dem Speichersystem integrieren.  Um mit dem Plug-in für Windows zu arbeiten, verwenden Sie die SnapCenter -Schnittstelle.

Das Plug-in für Windows umfasst die folgenden Hauptfunktionen:

* *Einheitliche grafische Benutzeroberfläche mit SnapCenter*
+
Die SnapCenter Schnittstelle bietet Ihnen Standardisierung und Konsistenz über Plug-Ins und Umgebungen hinweg.  Über die SnapCenter Schnittstelle können Sie konsistente Sicherungs- und Wiederherstellungsprozesse über alle Plug-Ins hinweg durchführen, zentralisierte Berichte verwenden, übersichtliche Dashboard-Ansichten nutzen, eine rollenbasierte Zugriffskontrolle (RBAC) einrichten und Jobs über alle Plug-Ins hinweg überwachen.  SnapCenter bietet außerdem eine zentrale Planung und Richtlinienverwaltung zur Unterstützung von Sicherungs- und Klonvorgängen.

* *Automatisierte zentrale Verwaltung*
+
Sie können routinemäßige Dateisystemsicherungen planen, eine richtlinienbasierte Sicherungsaufbewahrung konfigurieren und Wiederherstellungsvorgänge einrichten.  Sie können Ihre Dateisystemumgebung auch proaktiv überwachen, indem Sie SnapCenter so konfigurieren, dass E-Mail-Benachrichtigungen gesendet werden.

* *Unterbrechungsfreie NetApp Snapshot-Technologie*
+
Das Plug-in für Windows verwendet die NetApp Snapshot-Technologie.  Auf diese Weise können Sie Dateisysteme in Sekundenschnelle sichern und schnell wiederherstellen, ohne den Host offline zu nehmen.  Snapshots verbrauchen nur minimalen Speicherplatz.



Zusätzlich zu diesen Hauptfunktionen bietet das Plug-in für Windows die folgenden Vorteile:

* Unterstützung für Sicherungs-, Wiederherstellungs- und Klon-Workflows
* RBAC-gestützte Sicherheit und zentralisierte Rollendelegierung
* Erstellung platzsparender Kopien von Produktionsdateisystemen zum Testen oder zur Datenextraktion mithilfe der NetApp FlexClone -Technologie
+
Informationen zur FlexClone -Lizenzierung finden Sie unterlink:../get-started/concept_snapcenter_licenses.html["SnapCenter -Lizenzen"^] .

* Möglichkeit, mehrere Backups gleichzeitig auf mehreren Servern auszuführen
* PowerShell-Cmdlets zum Skripting von Sicherungs-, Wiederherstellungs- und Klonvorgängen
* Unterstützung für die Sicherung von Dateisystemen und virtuellen Maschinendatenträgern (VMDKs)
* Unterstützung für physische und virtualisierte Infrastrukturen
* Unterstützung für iSCSI, Fibre Channel, FCoE, Raw Device Mapping (RDM), Asymmetric LUN Mapping (ALM), VMDK über NFS und VMFS sowie virtuelles FC
* Unterstützung für Non-Volatile Memory Express (NVMe) auf Windows Server 2022
+
** Sicherungs-, Wiederherstellungs-, Klon- und Überprüfungs-Workflows auf VMDK-Layout, das auf NVMe über TCP/IP erstellt wurde.
** Unterstützt NVMe-Firmwareversion 1.3 ab ESX 8.0 Update 2 und erfordert virtuelle Hardwareversion 21.
** Windows Server Failover Clustering (WSFC) wird für Anwendungen über VMDK auf NVMe über TCP/IP nicht unterstützt.


* Unterstützt SnapMirror Active Sync (ursprünglich veröffentlicht als SnapMirror Business Continuity [SM-BC]), wodurch Geschäftsdienste auch bei einem vollständigen Site-Ausfall weiter ausgeführt werden können und Anwendungen mithilfe einer sekundären Kopie transparent ausfallen können.  Um mit SnapMirror Active Sync ein Failover auszulösen, sind weder manuelle Eingriffe noch zusätzliche Skripts erforderlich.

