---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: Sie können SnapCenter verwenden, um Dateisystemsicherungen wiederherzustellen.  Die Wiederherstellung des Dateisystems ist ein mehrphasiger Prozess, bei dem alle Daten aus einer angegebenen Sicherung an den ursprünglichen Speicherort des Dateisystems kopiert werden. 
---
= Wiederherstellen von Windows-Dateisystemsicherungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können SnapCenter verwenden, um Dateisystemsicherungen wiederherzustellen.  Die Wiederherstellung des Dateisystems ist ein mehrphasiger Prozess, bei dem alle Daten aus einer angegebenen Sicherung an den ursprünglichen Speicherort des Dateisystems kopiert werden.

.Bevor Sie beginnen
* Sie müssen das Dateisystem gesichert haben.
* Wenn für ein Dateisystem gerade ein geplanter Vorgang ausgeführt wird, beispielsweise ein Sicherungsvorgang, muss dieser Vorgang abgebrochen werden, bevor Sie einen Wiederherstellungsvorgang starten können.
* Sie können eine Dateisystemsicherung nur am ursprünglichen Speicherort wiederherstellen, nicht auf einem alternativen Pfad.
+
Sie können aus einer Sicherung keine einzelne Datei wiederherstellen, da das wiederhergestellte Dateisystem alle Daten am ursprünglichen Speicherort des Dateisystems überschreibt.  Um eine einzelne Datei aus einer Dateisystemsicherung wiederherzustellen, müssen Sie die Sicherung klonen und auf die Datei im Klon zugreifen.

* Sie können ein System- oder Startvolume nicht wiederherstellen.
* SnapCenter kann Dateisysteme in einem Windows-Cluster wiederherstellen, ohne die Clustergruppe offline zu nehmen.


.Informationen zu diesem Vorgang
* Der SCRIPTS_PATH wird mithilfe des Schlüssels „PredefinedWindowsScriptsDirectory“ definiert, der sich in der Datei „SMCoreServiceHost.exe.Config“ des Plug-In-Hosts befindet.
+
Bei Bedarf können Sie diesen Pfad ändern und den SMcore-Dienst neu starten.  Aus Sicherheitsgründen wird empfohlen, den Standardpfad zu verwenden.

+
Der Wert des Schlüssels kann von Swagger über die API angezeigt werden: API /4.7/configsettings

+
Sie können die GET-API verwenden, um den Wert des Schlüssels anzuzeigen.  SET-API wird nicht unterstützt.

* Für den Wiederherstellungsvorgang mit SnapMirror Active Sync müssen Sie die Sicherung vom primären Speicherort auswählen.
* Bei ONTAP 9.12.1 und niedrigeren Versionen erben die im Rahmen der Wiederherstellung aus den SnapLock Vault-Snapshots erstellten Klone die Ablaufzeit von SnapLock Vault. Der Speicheradministrator sollte die Klone nach Ablauf des SnapLock manuell bereinigen.


[role="tabbed-block"]
====
.SnapCenter -Benutzeroberfläche
--
.Schritte
. Klicken Sie im linken Navigationsbereich auf *Ressourcen* und wählen Sie dann das entsprechende Plug-In aus der Liste aus.
. Um die Liste der Ressourcen zu filtern, wählen Sie die Optionen „Dateisystem“ und „Ressourcengruppe“ aus.
. Wählen Sie eine Ressourcengruppe aus der Liste aus und klicken Sie dann auf *Wiederherstellen*.
. Wählen Sie auf der Seite „Sicherungen“ aus, ob Sie von primären oder sekundären Speichersystemen wiederherstellen möchten, und wählen Sie dann eine wiederherzustellende Sicherung aus.
. Wählen Sie Ihre Optionen im Wiederherstellungsassistenten aus.
. Sie können den Pfad und die Argumente des Präskripts oder Postskripts eingeben, das SnapCenter vor bzw. nach dem Wiederherstellungsvorgang ausführen soll.
+
Sie können beispielsweise ein Skript ausführen, um SNMP-Traps zu aktualisieren, Warnungen zu automatisieren, Protokolle zu senden usw.

+

NOTE: Der Prescripts- oder Postscripts-Pfad sollte keine Laufwerke oder Freigaben enthalten.  Der Pfad sollte relativ zum SCRIPTS_PATH sein.

. Wählen Sie auf der Benachrichtigungsseite eine der folgenden Optionen aus:
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Protokollieren Sie SnapCenter Serverereignisse im Syslog des Speichersystems
 a| 
Wählen Sie diese Option, um SnapCenter Server-Ereignisse im Syslog des Speichersystems zu protokollieren.



 a| 
Senden Sie eine AutoSupport -Benachrichtigung für fehlgeschlagene Vorgänge an das Speichersystem
 a| 
Wählen Sie diese Option, um Informationen zu fehlgeschlagenen Vorgängen mithilfe von AutoSupport an NetApp zu senden.



 a| 
E-Mail-Präferenz
 a| 
Wählen Sie *Immer*, *Bei Fehler* oder *Bei Fehler oder Warnung* aus, um nach der Wiederherstellung von Sicherungen E-Mail-Nachrichten an die Empfänger zu senden.  Geben Sie den SMTP-Server, die Standard-Betreffzeile der E-Mail sowie die E-Mail-Adressen „An“ und „Von“ ein.

|===
. Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig*.
. Überwachen Sie den Vorgangsfortschritt, indem Sie auf *Überwachen* > *Jobs* klicken.



IMPORTANT: Wenn das wiederhergestellte Dateisystem eine Datenbank enthält, müssen Sie auch die Datenbank wiederherstellen.  Wenn Sie die Datenbank nicht wiederherstellen, befindet sich Ihre Datenbank möglicherweise in einem ungültigen Zustand.  Informationen zum Wiederherstellen von Datenbanken finden Sie im Datenschutzhandbuch für die jeweilige Datenbank.

--
.PowerShell-Cmdlets
--
.Schritte
. Initiieren Sie mithilfe des Cmdlets Open-SmConnection eine Verbindungssitzung mit dem SnapCenter -Server für einen angegebenen Benutzer.
+
[listing]
----
PS C:\> Open-Smconnection
----
. Rufen Sie die Informationen zu den Sicherungen ab, die Sie wiederherstellen möchten, indem Sie die Cmdlets „Get-SmBackup“ und „Get-SmBackupReport“ verwenden.
+
Dieses Beispiel zeigt Informationen zu allen verfügbaren Backups an:

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
  1               Payroll Dataset_vise-f6_08... 8/4/2015    11:02:32 AM                 Full Backup
  2               Payroll Dataset_vise-f6_08... 8/4/2015    11:23:17 AM
----
+
Dieses Beispiel zeigt detaillierte Informationen zum Backup vom 29. Januar 2015 bis 3. Februar 2015:

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

   SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. Stellen Sie Daten aus der Sicherung mithilfe des Cmdlets Restore-SmBackup wieder her.
+
[listing]
----
Restore-SmBackup -PluginCode 'DummyPlugin' -AppObjectId 'scc54.sccore.test.com\DummyPlugin\NTP\DB1' -BackupId 269 -Confirm:$false
output:
Name                : Restore 'scc54.sccore.test.com\DummyPlugin\NTP\DB1'
Id                  : 2368
StartTime           : 10/4/2016 11:22:02 PM
EndTime             :
IsCancellable       : False
IsRestartable       : False
IsCompleted         : False
IsVisible           : True
IsScheduled         : False
PercentageCompleted : 0
Description         :
Status              : Queued
Owner               :
Error               :
Priority            : None
Tasks               : {}
ParentJobID         : 0
EventId             : 0
JobTypeId           :
ApisJobKey          :
ObjectId            : 0
PluginCode          : NONE
PluginName          :
----


Informationen zu den mit dem Cmdlet verwendbaren Parametern und deren Beschreibungen erhalten Sie durch Ausführen von _Get-Help command_name_. Alternativ können Sie auch auf die https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Referenzhandbuch für SnapCenter -Software-Cmdlets"^] .

--
====