---
permalink: upgrade/upgrade_snapcenter_server_linux.html 
sidebar: sidebar 
keywords: upgrade, upgrade snapcenter server, linux 
summary: Sie können die SnapCenter Server-Installationsdatei verwenden, um den SnapCenter Server zu aktualisieren. 
---
= Aktualisieren Sie den SnapCenter -Server auf dem Linux-Host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die SnapCenter Server-Installationsdatei verwenden, um den SnapCenter Server zu aktualisieren.

*Schritte*

. Führen Sie eine der Aktionen aus, um den SnapCenter -Server zu aktualisieren.
+
|===
| Wenn Sie auftreten möchten ... | Machen Sie Folgendes... 


 a| 
Nicht interaktives Upgrade
 a| 
`sudo ./snapcenter-linux-server-(el8/el9/sles15).bin -i silent -DUPGRADE=<value> -DINSTALL_LOG_NAME=<filename>`

Beispiel: sudo ./snapcenter_linux_server.bin -i silent -DUPGRADE=1 -DINSTALL_LOG_NAME=InstallerLog.log

Protokolle werden unter _/var/opt/snapcenter/logs_ gespeichert.

Für das Upgrade zu übergebende Parameter:

** DINSTALL_LOG_NAME: Name der Protokolldatei, in der die Installationsprotokolle gespeichert werden.
** DUPGRADE: Der Standardwert ist 0.  Geben Sie diesen Parameter und seinen Wert als eine beliebige Ganzzahl ungleich 0 an, um den SnapCenter -Server zu aktualisieren.




 a| 
Interaktive Installation
 a| 
`./snapcenter-linux-server-(el8/el9/sles15).bin`

Sie werden zur Bestätigung des Upgrades aufgefordert.  Geben Sie einen beliebigen Wert außer 0 ein, um das SnapCenter Server-Upgrade zu bestätigen.

|===



NOTE: Sie sollten sich entweder abmelden und dann bei SnapCenter anmelden oder den Browser schließen und dann einen neuen öffnen, um auf die SnapCenter -GUI zuzugreifen.
