---
permalink: protect-hana/concept_how_resources_resource_groups_and_policies_are_used_for_protecting_sap_hana_databases.html 
sidebar: sidebar 
keywords: SAP HANA databases 
summary: Bevor Sie SnapCenter verwenden, ist es hilfreich, die grundlegenden Konzepte im Zusammenhang mit den Sicherungs-, Klon- und Wiederherstellungsvorgängen zu verstehen, die Sie durchführen möchten.  Sie interagieren mit Ressourcen, Ressourcengruppen und Richtlinien für verschiedene Vorgänge. 
---
= So werden Ressourcen, Ressourcengruppen und Richtlinien zum Schutz von SAP HANA-Datenbanken verwendet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie SnapCenter verwenden, ist es hilfreich, die grundlegenden Konzepte im Zusammenhang mit den Sicherungs-, Klon- und Wiederherstellungsvorgängen zu verstehen, die Sie durchführen möchten.  Sie interagieren mit Ressourcen, Ressourcengruppen und Richtlinien für verschiedene Vorgänge.

* Bei den Ressourcen handelt es sich typischerweise um SAP HANA-Datenbanken, die Sie mit SnapCenter sichern oder klonen.
* Eine SnapCenter Ressourcengruppe ist eine Sammlung von Ressourcen auf einem Host.
+
Wenn Sie einen Vorgang für eine Ressourcengruppe ausführen, führen Sie diesen Vorgang für die in der Ressourcengruppe definierten Ressourcen gemäß dem Zeitplan aus, den Sie für die Ressourcengruppe angeben.

+
Sie können bei Bedarf eine einzelne Ressource oder eine Ressourcengruppe sichern.  Sie können auch geplante Sicherungen für einzelne Ressourcen und Ressourcengruppen durchführen.

* Die Richtlinien legen die Sicherungshäufigkeit, Replikation, Skripte und andere Merkmale von Datenschutzvorgängen fest.
+
Wenn Sie eine Ressourcengruppe erstellen, wählen Sie eine oder mehrere Richtlinien für diese Gruppe aus.  Sie können auch eine Richtlinie auswählen, wenn Sie eine bedarfsgesteuerte Sicherung für eine einzelne Ressource durchführen.



Stellen Sie sich eine Ressourcengruppe so vor, dass sie definiert, was Sie schützen möchten und wann Sie es hinsichtlich Tag und Uhrzeit schützen möchten.  Stellen Sie sich eine Richtlinie so vor, als ob sie definiert, wie Sie sie schützen möchten.  Wenn Sie beispielsweise alle Datenbanken sichern, können Sie eine Ressourcengruppe erstellen, die alle Datenbanken im Host enthält.  Sie könnten dann zwei Richtlinien an die Ressourcengruppe anhängen: eine tägliche Richtlinie und eine stündliche Richtlinie.  Wenn Sie die Ressourcengruppe erstellen und die Richtlinien anhängen, können Sie die Ressourcengruppe so konfigurieren, dass täglich eine vollständige Sicherung durchgeführt wird.
