---
permalink: protect-hana/reference_types_of_restore_strategies_supported_for_manually_added_sap_hana_resources.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Sie müssen eine Strategie definieren, bevor Sie Wiederherstellungsvorgänge mit SnapCenter erfolgreich durchführen können.  Es gibt zwei Arten von Wiederherstellungsstrategien für manuell hinzugefügte SAP HANA-Ressourcen.  Sie können manuell hinzugefügte SAP HANA-Ressourcen nicht wiederherstellen. 
---
= Unterstützte Wiederherstellungsstrategien für manuell hinzugefügte SAP HANA-Ressourcen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen eine Strategie definieren, bevor Sie Wiederherstellungsvorgänge mit SnapCenter erfolgreich durchführen können.  Es gibt zwei Arten von Wiederherstellungsstrategien für manuell hinzugefügte SAP HANA-Ressourcen.  Sie können manuell hinzugefügte SAP HANA-Ressourcen nicht wiederherstellen.


NOTE: Sie können manuell hinzugefügte SAP HANA-Ressourcen nicht wiederherstellen.



== Vollständige Ressourcenwiederherstellung

* Stellt alle Volumes, Qtrees und LUNs einer Ressource wieder her



NOTE: Wenn die Ressource Volumes oder Qtrees enthält, werden die Snapshots, die nach dem zur Wiederherstellung ausgewählten Snapshot auf diesen Volumes oder Qtrees erstellt wurden, gelöscht und können nicht wiederhergestellt werden.  Wenn außerdem eine andere Ressource auf denselben Volumes oder Qtrees gehostet wird, wird diese Ressource ebenfalls gelöscht.



== Wiederherstellung auf Dateiebene

* Stellt Dateien aus Volumes, Qtrees oder Verzeichnissen wieder her
* Stellt nur die ausgewählten LUNs wieder her

