---
permalink: protect-hana/task_create_backup_policies_for_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: Bevor Sie SnapCenter zum Sichern von SAP HANA-Datenbankressourcen verwenden, müssen Sie eine Sicherungsrichtlinie für die Ressource oder Ressourcengruppe erstellen, die Sie sichern möchten.  Eine Sicherungsrichtlinie ist ein Satz von Regeln, der regelt, wie Sie Sicherungen verwalten, planen und aufbewahren. 
---
= Erstellen von Sicherungsrichtlinien für SAP HANA-Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie SnapCenter zum Sichern von SAP HANA-Datenbankressourcen verwenden, müssen Sie eine Sicherungsrichtlinie für die Ressource oder Ressourcengruppe erstellen, die Sie sichern möchten.  Eine Sicherungsrichtlinie ist ein Satz von Regeln, der regelt, wie Sie Sicherungen verwalten, planen und aufbewahren.

.Bevor Sie beginnen
* Sie müssen Ihre Sicherungsstrategie definiert haben.
+
Einzelheiten finden Sie in den Informationen zum Definieren einer Datenschutzstrategie für SAP HANA-Datenbanken.

* Sie müssen sich auf den Datenschutz vorbereitet haben, indem Sie Aufgaben wie die Installation von SnapCenter, das Hinzufügen von Hosts, das Einrichten von Speichersystemverbindungen und das Hinzufügen von Ressourcen abgeschlossen haben.
* Wenn Sie Snapshots auf einen Spiegel oder Tresor replizieren, muss Ihnen der SnapCenter Administrator die SVMs für das Quell- und das Zielvolume zugewiesen haben.
+
Darüber hinaus können Sie in der Richtlinie Replikations-, Skript- und Anwendungseinstellungen angeben.  Diese Optionen sparen Zeit, wenn Sie die Richtlinie für eine andere Ressourcengruppe wiederverwenden möchten.

* Überprüfen Sie die spezifischen Voraussetzungen und Einschränkungen der SnapMirror Active Sync.  Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Objektlimits für SnapMirror Active Sync"] .


.Informationen zu diesem Vorgang
* SAP HANA-Systemreplikation
+
** Sie können das primäre SAP HANA-System schützen und alle Datenschutzvorgänge durchführen.
** Sie können das sekundäre SAP HANA-System schützen, aber die Sicherungen können nicht erstellt werden.
+
Nach dem Failover können alle Datenschutzvorgänge durchgeführt werden, da das sekundäre SAP HANA-System zum primären SAP HANA-System wird.

+
Sie können kein Backup für das SAP HANA-Datenvolumen erstellen, aber SnapCenter schützt weiterhin die Nicht-Datenvolumes (NDV).



* SnapLock
+
** Wenn die Option „Sicherungskopien für eine bestimmte Anzahl von Tagen aufbewahren“ ausgewählt ist, muss die SnapLock -Aufbewahrungsdauer kleiner oder gleich der angegebenen Aufbewahrungsdauer in Tagen sein.
** Durch die Angabe einer Snapshot-Sperrfrist wird das Löschen der Snapshots verhindert, bis die Aufbewahrungsfrist abgelaufen ist. Dies kann dazu führen, dass mehr Snapshots aufbewahrt werden als in der Richtlinie angegeben.
** Bei ONTAP 9.12.1 und niedrigeren Versionen erben die im Rahmen der Wiederherstellung aus den SnapLock Vault-Snapshots erstellten Klone die Ablaufzeit von SnapLock Vault. Der Speicheradministrator sollte die Klone nach Ablauf des SnapLock manuell bereinigen.




.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite „Einstellungen“ auf *Richtlinien*.
. Klicken Sie auf *Neu*.
. Geben Sie auf der Seite „Name“ den Richtliniennamen und die Details ein.
. Führen Sie auf der Seite „Richtlinientyp“ die folgenden Schritte aus:
+
** Speichertyp auswählen
** Wählen Sie den Sicherungstyp:
+
|===
| Wenn Sie wollen... | Machen Sie Folgendes... 


 a| 
Erstellen Sie ein Backup mit der Snapshot-Technologie
 a| 
Wählen Sie *Snapshot-basiert*.



 a| 
Führen Sie eine Integritätsprüfung der Datenbank durch
 a| 
Wählen Sie *Dateibasiertes Backup*.  Es werden nur aktive Mandanten gesichert.

|===


. Führen Sie auf der Seite „Snapshot und Replikation“ die folgenden Schritte aus:
+
** Geben Sie den Zeitplantyp an, indem Sie *Auf Anfrage*, *Stündlich*, *Täglich*, *Wöchentlich* oder *Monatlich* auswählen.
+

NOTE: Sie können den Zeitplan (Startdatum, Enddatum und Häufigkeit) für den Sicherungsvorgang beim Erstellen einer Ressourcengruppe angeben.  Auf diese Weise können Sie Ressourcengruppen erstellen, die dieselbe Richtlinie und Sicherungshäufigkeit verwenden, aber auch jeder Richtlinie unterschiedliche Sicherungszeitpläne zuweisen.

+

NOTE: Wenn Sie 2:00 Uhr morgens geplant haben, wird der Zeitplan während der Sommerzeit (DST) nicht ausgelöst.



. Geben Sie auf der Seite „Snapshot und Replikation“ die Aufbewahrungseinstellungen für den Sicherungstyp und den Zeitplantyp an, der auf der Seite „Sicherungstyp“ ausgewählt wurde:
+
|===
| Wenn Sie wollen... | Dann... 


 a| 
Behalten Sie eine bestimmte Anzahl von Snapshots
 a| 
Wählen Sie *Zu behaltende Kopien* und geben Sie dann die Anzahl der Snapshots an, die Sie behalten möchten.

Wenn die Anzahl der Snapshots die angegebene Anzahl überschreitet, werden zuerst die ältesten Snapshots gelöscht.


NOTE: Der maximale Aufbewahrungswert beträgt 1018. Sicherungen schlagen fehl, wenn die Aufbewahrung auf einen höheren Wert eingestellt ist, als von der ONTAP Version unterstützt wird.


IMPORTANT: Für Snapshot-Kopien-basierte Backups müssen Sie die Aufbewahrungsanzahl auf 2 oder höher einstellen, wenn Sie die SnapVault -Replikation aktivieren möchten.  Wenn Sie die Aufbewahrungsanzahl auf 1 setzen, schlägt der Aufbewahrungsvorgang möglicherweise fehl, da der erste Snapshot der Referenz-Snapshot für die SnapVault -Beziehung ist, bis ein neuerer Snapshot auf das Ziel repliziert wird.


NOTE: Für die SAP HANA-Systemreplikation wird empfohlen, alle Ressourcen des SAP HANA-Systems zu einer Ressourcengruppe hinzuzufügen.  Dadurch wird sichergestellt, dass die richtige Anzahl an Sicherungen aufbewahrt wird.


NOTE: Bei der SAP HANA-Systemreplikation entspricht die Gesamtzahl der erstellten Snapshots der für die Ressourcengruppe festgelegten Aufbewahrungsdauer.  Das Entfernen des ältesten Snapshots hängt davon ab, auf welchem Knoten sich der älteste Snapshot befindet.  Beispielsweise ist die Aufbewahrung für eine Ressourcengruppe mit der primären SAP HANA-Systemreplikation und der sekundären SAP HANA-Systemreplikation auf 7 festgelegt.  Sie können maximal 7 Snapshots gleichzeitig erstellen, sowohl die primäre als auch die sekundäre SAP HANA-Systemreplikation.



 a| 
Bewahren Sie die Snapshots für eine bestimmte Anzahl von Tagen auf
 a| 
Wählen Sie *Kopien aufbewahren für* und geben Sie dann die Anzahl der Tage an, für die Sie die Snapshots aufbewahren möchten, bevor sie gelöscht werden.



 a| 
Sperrzeitraum für Snapshot-Kopien
 a| 
Wählen Sie *Sperrzeitraum für Snapshot-Kopien* und geben Sie Tage, Monate oder Jahre an.

Die Aufbewahrungsdauer von SnapLock sollte weniger als 100 Jahre betragen.

|===
. Wählen Sie eine Snapshot-Bezeichnung aus.
+

NOTE: Sie können primären Snapshots SnapMirror Labels für die Remote-Replikation zuweisen, sodass die primären Snapshots den Snapshot-Replikationsvorgang von SnapCenter auf sekundäre ONTAP -Systeme auslagern können. Dies kann erfolgen, ohne die Option SnapMirror oder SnapVault auf der Richtlinienseite zu aktivieren.

. Wählen Sie für auf Snapshot-Kopien basierende Sicherungen im Abschnitt „Sekundäre Replikationsoptionen auswählen“ eine oder beide der folgenden sekundären Replikationsoptionen aus:
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
*Aktualisieren Sie SnapMirror , nachdem Sie eine lokale Snapshot-Kopie erstellt haben*
 a| 
Wählen Sie dieses Feld aus, um Spiegelkopien der Sicherungssätze auf einem anderen Volume zu erstellen (SnapMirror -Replikation).

Diese Option sollte für die aktive Synchronisierung von SnapMirror aktiviert werden.

Wenn die Schutzbeziehung in ONTAP vom Typ „Mirror und Vault“ ist und Sie nur diese Option auswählen, wird der auf dem primären Server erstellte Snapshot nicht an das Ziel übertragen, sondern im Ziel aufgelistet.  Wenn dieser Snapshot vom Ziel ausgewählt wird, um einen Wiederherstellungsvorgang durchzuführen, wird die Fehlermeldung „Der sekundäre Speicherort ist für die ausgewählte gewölbte/gespiegelte Sicherung nicht verfügbar“ angezeigt.

Während der sekundären Replikation lädt die Ablaufzeit des SnapLock die Ablaufzeit des primären SnapLock .

Durch Klicken auf die Schaltfläche *Aktualisieren* auf der Seite „Topologie“ werden die Ablaufzeiten des sekundären und primären SnapLock aktualisiert, die von ONTAP abgerufen werden.

Sehen link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Anzeigen von SAP HANA-Datenbanksicherungen und -klonen auf der Seite „Topologie“"] .



 a| 
*Aktualisieren Sie SnapVault , nachdem Sie eine lokale Snapshot-Kopie erstellt haben*
 a| 
Wählen Sie diese Option, um eine Backup-Replikation von Festplatte zu Festplatte durchzuführen (SnapVault -Backups).

Während der sekundären Replikation lädt die Ablaufzeit des SnapLock die Ablaufzeit des primären SnapLock .  Durch Klicken auf die Schaltfläche *Aktualisieren* auf der Seite „Topologie“ werden die Ablaufzeiten des sekundären und primären SnapLock aktualisiert, die von ONTAP abgerufen werden.

Wenn SnapLock nur auf dem sekundären Server von ONTAP , bekannt als SnapLock Vault, konfiguriert ist, wird durch Klicken auf die Schaltfläche *Aktualisieren* auf der Seite „Topologie“ die Sperrdauer auf dem sekundären Server aktualisiert, die von ONTAP abgerufen wird.

Weitere Informationen zu SnapLock Vault finden Sie unter https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Übertragen Sie Snapshot-Kopien in WORM auf einem Tresorziel"]

Sehen link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Anzeigen von SAP HANA-Datenbanksicherungen und -klonen auf der Seite „Topologie“"] .



 a| 
*Fehler bei der Wiederholungsanzahl*
 a| 
Geben Sie die maximale Anzahl an Replikationsversuchen ein, die zulässig sind, bevor der Vorgang beendet wird.

|===
+

NOTE: Sie sollten die SnapMirror Aufbewahrungsrichtlinie in ONTAP für den sekundären Speicher konfigurieren, um zu vermeiden, dass das maximale Limit für Snapshots auf dem sekundären Speicher erreicht wird.

. Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig*.

