= 
:allow-uri-read: 


Sie können entweder die standardmäßige Snapshot-Benennungskonvention oder eine benutzerdefinierte Benennungskonvention verwenden.  Die standardmäßige Namenskonvention für Backups fügt den Snapshot-Namen einen Zeitstempel hinzu, der Ihnen hilft, den Zeitpunkt der Erstellung der Kopien zu identifizieren.

Der Snapshot verwendet die folgende Standardbenennungskonvention:

`resourcegroupname_hostname_timestamp`

Sie sollten Ihre Backup-Ressourcengruppen logisch benennen, wie im folgenden Beispiel:

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
In diesem Beispiel haben die Syntaxelemente folgende Bedeutung:

* _dts1_ ist der Name der Ressourcengruppe.
* _mach1x88_ ist der Hostname.
* _03-12-2015_23.17.26_ ist das Datum und der Zeitstempel.


Alternativ können Sie das Snapshot-Namensformat beim Schützen von Ressourcen oder Ressourcengruppen angeben, indem Sie *Benutzerdefiniertes Namensformat für Snapshot-Kopie verwenden* auswählen.  Beispiel: customtext_resourcegroup_policy_hostname oder resourcegroup_hostname.  Standardmäßig wird dem Snapshot-Namen das Zeitstempel-Suffix hinzugefügt.
