= 
:allow-uri-read: 


Sie müssen eine Verbindung zur Storage Virtual Machine (SVM) und Anmeldeinformationen erstellen, bevor Sie PowerShell-Cmdlets zum Ausführen von Datenschutzvorgängen verwenden.

.Bevor Sie beginnen
* Sie sollten die PowerShell-Umgebung für die Ausführung der PowerShell-Cmdlets vorbereitet haben.
* Sie sollten über die erforderlichen Berechtigungen in der Rolle „Infrastrukturadministrator“ verfügen, um Speicherverbindungen zu erstellen.
* Sie sollten sicherstellen, dass die Plug-In-Installationen nicht im Gange sind.
+
Während des Hinzufügens einer Speichersystemverbindung dürfen keine Host-Plug-In-Installationen ausgeführt werden, da der Host-Cache möglicherweise nicht aktualisiert wird und der Datenbankstatus in der SnapCenter -GUI möglicherweise als „Nicht für Sicherung verfügbar“ oder „Nicht auf NetApp -Speicher“ angezeigt wird.

* Speichersystemnamen sollten eindeutig sein.
+
SnapCenter unterstützt nicht mehrere Speichersysteme mit demselben Namen auf verschiedenen Clustern.  Jedes von SnapCenter unterstützte Speichersystem sollte einen eindeutigen Namen und eine eindeutige Verwaltungs-LIF-IP-Adresse haben.



.Schritte
. Initiieren Sie eine PowerShell Core-Verbindungssitzung mithilfe des Cmdlets Open-SmConnection.
+
Dieses Beispiel öffnet eine PowerShell-Sitzung:

+
[listing]
----
PS C:\> Open-SmConnection
----
. Erstellen Sie mithilfe des Cmdlets Add-SmStorageConnection eine neue Verbindung zum Speichersystem.
+
In diesem Beispiel wird eine neue Speichersystemverbindung erstellt:

+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Erstellen Sie mithilfe des Cmdlets Add-SmCredential neue Anmeldeinformationen.
+
In diesem Beispiel wird eine neue Anmeldeinformation mit dem Namen „FinanceAdmin“ mit Windows-Anmeldeinformationen erstellt:

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----


Informationen zu den mit dem Cmdlet verwendbaren Parametern und deren Beschreibungen erhalten Sie durch Ausführen von _Get-Help command_name_. Alternativ können Sie auch auf die https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Referenzhandbuch für SnapCenter -Software-Cmdlets"^] .
