---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: Erstellen Sie die Azure-Anmeldeinformationen in SnapCenter , um auf das Azure NetApp -Konto zuzugreifen. 
---
= Erstellen der Azure-Anmeldeinformationen in SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die Azure-Anmeldeinformationen in SnapCenter erstellen, um auf das Azure NetApp -Konto zuzugreifen.

.Bevor Sie beginnen
* Stellen Sie sicher, dass Sie den Dienstprinzipal in Azure erstellt haben.
* Stellen Sie sicher, dass Sie über die Mandanten-ID, die Client-ID und den geheimen Schlüssel verfügen, die mit dem Dienstprinzipal verknüpft sind.
+
** Die Mandanten-ID finden Sie im Azure-Portal auf der Übersichtsseite für die Entra-ID.
** Die Client-ID wird auch als Anwendungs-ID für den Enterprise-App-/Service-Principal bezeichnet.  Dies finden Sie im Azure-Portal auf der Übersichtsseite für die Unternehmensanwendung, die Sie als Dienstprinzipal für SnapCenter erstellt haben.
** Der geheime Clientschlüssel wird auch als geheimer Wert bezeichnet.  Sie können dieses Clientgeheimnis im Azure-Portal erstellen, indem Sie unter Entra ID zu *App-Registrierungen* navigieren.  Nachdem Sie die von Ihnen erstellte Enterprise-App ausgewählt haben, navigieren Sie zu *Zertifikate und Geheimnisse* und dann zu *Neues Client-Geheimnis*.
+

NOTE: Auf den geheimen Wert kann nur zugegriffen werden, wenn er erstellt wurde.  Sie können später nicht mehr darauf zugreifen.

** Dem Dienstprinzipal müssen Berechtigungen erteilt werden.  Die Rolle des Mitwirkenden ermöglicht dem Dienstprinzipal, erforderliche Aktionen in Azure auszuführen.  Dies kann über die Zugriffssteuerungsseite (IAM) auf der Abonnementseite gewährt werden.




.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite „Einstellungen“ auf *Anmeldeinformationen*.
. Klicken Sie auf *Neu*.
. Geben Sie auf der Seite „Anmeldeinformationen“ die folgenden Informationen an, die zum Erstellen der Anmeldeinformationen erforderlich sind.
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Anmeldeinformationsname
 a| 
Geben Sie einen Namen für die Anmeldeinformationen ein.



 a| 
Authentifizierungsmodus
 a| 
Wählen Sie *Azure-Anmeldeinformationen* aus der Dropdownliste aus.



 a| 
Mandanten-ID
 a| 
Geben Sie die Mandanten-ID ein.



 a| 
Client-ID
 a| 
Geben Sie die Client-ID ein.



 a| 
Geheimer Clientschlüssel
 a| 
Geben Sie den geheimen Clientschlüssel ein.

|===
. Klicken Sie auf *OK*.

