---
permalink: protect-azure/create-backup-policies-sap-hana.html 
sidebar: sidebar 
keywords: create policies, SAP HANA, backup policies 
summary: Erstellen Sie eine Sicherungsrichtlinie für die Ressource oder Ressourcengruppe, die Sie sichern möchten. 
---
= Erstellen von Sicherungsrichtlinien für SAP HANA-Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie SnapCenter zum Sichern von SAP HANA-Datenbankressourcen verwenden, müssen Sie eine Sicherungsrichtlinie für die Ressource oder Ressourcengruppe erstellen, die Sie sichern möchten.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite „Einstellungen“ auf *Richtlinien*.
. Klicken Sie auf *Neu*.
. Geben Sie auf der Seite „Name“ den Richtliniennamen und eine Beschreibung ein.
. Führen Sie auf der Seite „Richtlinientyp“ die folgenden Schritte aus:
+
.. Wählen Sie als Speichertyp * Azure NetApp Files* aus.
.. Wählen Sie *Dateibasiert*, wenn Sie eine Integritätsprüfung der Datenbank durchführen möchten.
.. Wählen Sie *Snapshot-basiert*, wenn Sie ein Backup mithilfe der Snapshot-Technologie erstellen möchten.


. Führen Sie auf der Seite „Snapshot und Sicherung“ die folgenden Schritte aus:
+
.. Wählen Sie die Häufigkeit der geplanten Sicherung aus.
.. Geben Sie die Aufbewahrungseinstellungen an.
.. Wenn Sie die Azure NetApp Files -Sicherung aktivieren möchten, wählen Sie *Sicherung aktivieren* und geben Sie die Aufbewahrungseinstellungen an.


. Überprüfen Sie die Zusammenfassung und klicken Sie auf *Fertig*.

