---
permalink: protect-azure/create-credential-add-plugin-host.html 
sidebar: sidebar 
keywords: snapcenter, azure, credential, plug-in host 
summary: Erstellen Sie die Anmeldeinformationen, um den Plug-In-Host hinzuzufügen. 
---
= Erstellen Sie die Anmeldeinformationen zum Hinzufügen des Plug-In-Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter verwendet Anmeldeinformationen, um Benutzer für SnapCenter -Vorgänge zu authentifizieren.

Sie sollten Anmeldeinformationen für die Installation von SnapCenter Plug-Ins und zusätzliche Anmeldeinformationen für die Durchführung von Datenschutzvorgängen erstellen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite „Einstellungen“ auf *Anmeldeinformationen*.
. Klicken Sie auf *Neu*.
. Geben Sie auf der Seite „Anmeldeinformationen“ die folgenden Informationen an, die zum Erstellen der Anmeldeinformationen erforderlich sind.
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Anmeldeinformationsname
 a| 
Geben Sie einen Namen für die Anmeldeinformationen ein.



 a| 
Authentifizierungsmodus
 a| 
Wählen Sie den Authentifizierungsmodus aus der Dropdown-Liste aus.



 a| 
Authentifizierungstyp
 a| 
Wählen Sie entweder *Passwortbasiert* oder *SSH-Schlüsselbasiert* (nur für Linux-Host).



 a| 
Benutzername
 a| 
Geben Sie den Benutzernamen an.



 a| 
Passwort
 a| 
Wenn Sie die kennwortbasierte Authentifizierung ausgewählt haben, geben Sie das Kennwort an.



 a| 
Privater SSH-Schlüssel
 a| 
Wenn Sie die SSH-Schlüssel-basierte Authentifizierung ausgewählt haben, geben Sie den privaten Schlüssel an.



 a| 
Verwenden Sie Sudo-Berechtigungen
 a| 
Aktivieren Sie das Kontrollkästchen „Sudo-Berechtigungen verwenden“, wenn Sie Anmeldeinformationen für einen Nicht-Root-Benutzer erstellen.


NOTE: Dies gilt nur für Linux-Benutzer.

|===
. Klicken Sie auf *OK*.

