---
permalink: protect-postgresql/add-hosts-and-install-plug-in-packages-on-remote-hosts-postgresql.html 
sidebar: sidebar 
keywords: credentials 
summary: Sie müssen die SnapCenter -Seite „Host hinzufügen“ verwenden, um Hosts hinzuzufügen und dann die Plug-In-Pakete zu installieren.  Die Plug-Ins werden automatisch auf den Remote-Hosts installiert.  Sie können einen Host hinzufügen und Plug-In-Pakete entweder für einen einzelnen Host oder für einen Cluster installieren. 
---
= Hosts hinzufügen und Plug-in-Pakete auf Remote-Hosts installieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die SnapCenter -Seite „Host hinzufügen“ verwenden, um Hosts hinzuzufügen und dann die Plug-In-Pakete zu installieren.  Die Plug-Ins werden automatisch auf den Remote-Hosts installiert.  Sie können den Host hinzufügen und Plug-In-Pakete für einen einzelnen Host installieren.

.Bevor Sie beginnen
* Wenn das Betriebssystem des SnapCenter Server-Hosts Windows 2019 und das Betriebssystem des Plug-in-Hosts Windows 2022 ist, sollten Sie Folgendes durchführen:
+
** Upgrade auf Windows Server 2019 (OS Build 17763.5936) oder höher
** Upgrade auf Windows Server 2022 (OS Build 20348.2402) oder höher


* Sie müssen ein Benutzer sein, dem eine Rolle mit den Berechtigungen zum Installieren und Deinstallieren von Plug-Ins zugewiesen ist, beispielsweise die SnapCenter Administratorrolle.
* Wenn Sie beim Installieren eines Plug-Ins auf einem Windows-Host Anmeldeinformationen angeben, die nicht integriert sind, oder wenn der Benutzer zu einem lokalen Arbeitsgruppenbenutzer gehört, müssen Sie die Benutzerkontensteuerung auf dem Host deaktivieren.
* Sie sollten sicherstellen, dass der Nachrichtenwarteschlangendienst ausgeführt wird.
* Die Administrationsdokumentation enthält Informationen zur Verwaltung von Hosts.
* Wenn Sie ein gruppenverwaltetes Dienstkonto (gMSA) verwenden, sollten Sie gMSA mit Administratorrechten konfigurieren.
+
link:../protect-postgresql/configure-gMSA-on-windows-server-2012-or-later.html["Konfigurieren Sie ein gruppenverwaltetes Dienstkonto auf Windows Server 2016 oder höher für PostgreSQL"]



.Informationen zu diesem Vorgang
* Sie können einen SnapCenter -Server nicht als Plug-In-Host zu einem anderen SnapCenter -Server hinzufügen.


.Schritte
. Klicken Sie im linken Navigationsbereich auf *Hosts*.
. Stellen Sie sicher, dass oben die Registerkarte *Verwaltete Hosts* ausgewählt ist.
. Klicken Sie auf *Hinzufügen*.
. Führen Sie auf der Seite „Hosts“ die folgenden Aktionen aus:
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Hosttyp
 a| 
Wählen Sie den Hosttyp aus:

** Windows
** Linux
+

NOTE: Das Plug-in für PostgreSQL wird auf dem PostgreSQL-Clienthost installiert und dieser Host kann entweder ein Windows- oder ein Linux-System sein.





 a| 
Hostname
 a| 
Geben Sie den Hostnamen für die Kommunikation ein.  Geben Sie den vollqualifizierten Domänennamen (FQDN) oder die IP-Adresse des Hosts ein.  SnapCenter ist auf die richtige Konfiguration des DNS angewiesen.  Daher empfiehlt es sich, den FQDN einzugeben.



 a| 
Anmeldeinformationen
 a| 
Wählen Sie entweder den von Ihnen erstellten Anmeldeinformationsnamen aus oder erstellen Sie neue Anmeldeinformationen.  Die Anmeldeinformationen müssen über Administratorrechte auf dem Remote-Host verfügen.  Einzelheiten finden Sie in den Informationen zum Erstellen von Anmeldeinformationen.

Sie können Details zu den Anmeldeinformationen anzeigen, indem Sie den Cursor über den von Ihnen angegebenen Anmeldeinformationsnamen bewegen.


NOTE: Der Authentifizierungsmodus für Anmeldeinformationen wird durch den Hosttyp bestimmt, den Sie im Assistenten „Host hinzufügen“ angeben.

|===
. Wählen Sie im Abschnitt „Zu installierende Plug-ins auswählen“ die zu installierenden Plug-ins aus.
+
Wenn Sie die REST-API zum Installieren des Plug-ins für PostgreSQL verwenden, müssen Sie die Version als 3.0 übergeben.  Beispiel: PostgreSQL:3.0

. (Optional) Klicken Sie auf *Weitere Optionen*.
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Hafen
 a| 
Behalten Sie entweder die Standard-Portnummer bei oder geben Sie die Portnummer an.  Die Standard-Portnummer ist 8145.  Wenn der SnapCenter -Server auf einem benutzerdefinierten Port installiert wurde, wird diese Portnummer als Standardport angezeigt.


NOTE: Wenn Sie die Plug-Ins manuell installiert und einen benutzerdefinierten Port angegeben haben, müssen Sie denselben Port angeben.  Andernfalls schlägt der Vorgang fehl.



 a| 
Installationspfad
 a| 
Das Plug-in für PostgreSQL wird auf dem PostgreSQL-Clienthost installiert und dieser Host kann entweder ein Windows- oder ein Linux-System sein.

** Für das SnapCenter Plug-ins-Paket für Windows ist der Standardpfad C:\Programme\ NetApp\ SnapCenter.  Optional können Sie den Pfad anpassen.
** Für das SnapCenter Plug-ins-Paket für Linux ist der Standardpfad /opt/ NetApp/snapcenter.  Optional können Sie den Pfad anpassen.




 a| 
Vorinstallationsprüfungen überspringen
 a| 
Aktivieren Sie dieses Kontrollkästchen, wenn Sie die Plug-ins bereits manuell installiert haben und nicht überprüfen möchten, ob der Host die Anforderungen für die Installation des Plug-ins erfüllt.



 a| 
Alle Hosts im Cluster hinzufügen
 a| 
Aktivieren Sie dieses Kontrollkästchen, um alle Clusterknoten hinzuzufügen.



 a| 
Verwenden Sie ein gruppenverwaltetes Dienstkonto (gMSA), um die Plug-In-Dienste auszuführen
 a| 
Aktivieren Sie für Windows-Hosts dieses Kontrollkästchen, wenn Sie zum Ausführen der Plug-In-Dienste ein gruppenverwaltetes Dienstkonto (gMSA) verwenden möchten.


NOTE: Geben Sie den gMSA-Namen im folgenden Format an: Domänenname\Kontoname$.


NOTE: gMSA wird nur als Anmeldedienstkonto für das SnapCenter -Plug-in für den Windows-Dienst verwendet.

|===
. Klicken Sie auf *Senden*.
+
Wenn Sie das Kontrollkästchen Vorabprüfungen überspringen nicht aktiviert haben, wird überprüft, ob der Host die Anforderungen für die Installation des Plug-Ins erfüllt. Speicherplatz, RAM, PowerShell-Version, .NET-Version, Speicherort (für Windows-Plug-Ins) und Java-Version (für Linux-Plug-Ins) werden anhand der Mindestanforderungen überprüft.  Werden die Mindestanforderungen nicht erfüllt, werden entsprechende Fehler- bzw. Warnmeldungen angezeigt.

+
Wenn der Fehler mit dem Speicherplatz oder RAM zusammenhängt, können Sie die Datei web.config unter C:\Programme\ NetApp\ SnapCenter WebApp aktualisieren, um die Standardwerte zu ändern.  Wenn der Fehler mit anderen Parametern zusammenhängt, müssen Sie das Problem beheben.

+

NOTE: Wenn Sie in einem HA-Setup die Datei web.config aktualisieren, müssen Sie die Datei auf beiden Knoten aktualisieren.

. Wenn der Hosttyp Linux ist, überprüfen Sie den Fingerabdruck und klicken Sie dann auf *Bestätigen und senden*.
+
In einer Cluster-Konfiguration sollten Sie den Fingerabdruck jedes Knotens im Cluster überprüfen.

+

NOTE: Die Überprüfung des Fingerabdrucks ist obligatorisch, auch wenn derselbe Host zuvor zu SnapCenter hinzugefügt und der Fingerabdruck bestätigt wurde.

. Überwachen Sie den Installationsfortschritt.
+
** Für Windows-Plug-Ins befinden sich die Installations- und Upgrade-Protokolle unter: _C:\Windows\ SnapCenter plugin\Install_<JOBID>\_
** Für Linux-Plug-Ins befinden sich die Installationsprotokolle unter: _/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Install_<JOBID>.log_ und die Upgrade-Protokolle unter: _/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Upgrade_<JOBID>.log_



