---
permalink: protect-postgresql/prerequisites-for-using-snapcenter-plug-in-for-postgresql.html 
sidebar: sidebar 
keywords: Credentials,SnapCenter Plug-in for postgresql 
summary: Bevor Sie das SnapCenter Plug-in für PostgreSQL verwenden, muss der SnapCenter Administrator den SnapCenter -Server installieren und konfigurieren und die erforderlichen Aufgaben ausführen. 
---
= Voraussetzungen für die Verwendung des SnapCenter -Plug-Ins für PostgreSQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie das SnapCenter Plug-in für PostgreSQL verwenden, muss der SnapCenter Administrator den SnapCenter -Server installieren und konfigurieren und die erforderlichen Aufgaben ausführen.

* Installieren und konfigurieren Sie SnapCenter Server.
* Melden Sie sich beim SnapCenter -Server an.
* Konfigurieren Sie die SnapCenter -Umgebung, indem Sie Speichersystemverbindungen hinzufügen und gegebenenfalls Anmeldeinformationen erstellen.
* Installieren Sie Java 11 auf Ihrem Linux- oder Windows-Host.
+
Sie müssen den Java-Pfad in der Umgebungspfadvariable des Hostcomputers festlegen.

* Richten Sie SnapMirror und SnapVault ein, wenn Sie eine Backup-Replikation wünschen.

