---
permalink: protect-postgresql/types-of-restore-performed-for-auto-discovered-postgresql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for postgresql 
summary: 'SnapCenter unterstützt Volume-basiertes SnapRestore (VBSR), Single File SnapRestore und Connect-and-Copy-Wiederherstellungstypen für automatisch erkannte PostgreSQL-Cluster.' 
---
= Arten von Wiederherstellungsvorgängen für automatisch erkanntes PostgreSQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SnapCenter -Plug-in für PostgreSQL unterstützt Single File SnapRestore und Connect-and-Copy-Wiederherstellungstypen für automatisch erkannte PostgreSQL-Cluster.



== Single File SnapRestore wird in NFS-Umgebungen für die folgenden Szenarien durchgeführt:

* Wenn nur die Option *Komplette Ressource* ausgewählt ist
* Wenn das ausgewählte Backup von einem SnapMirror oder SnapVault Sekundärspeicherort stammt und die Option *Complete Resource* ausgewählt ist




== Single File SnapRestore wird in SAN-Umgebungen für die folgenden Szenarien durchgeführt:

* Wenn nur die Option *Komplette Ressource* ausgewählt ist
* Wenn das Backup von einem SnapMirror oder SnapVault Sekundärspeicherort ausgewählt wird und die Option *Complete Resource* ausgewählt ist

