---
permalink: install/concept_create_and_manage_igroups.html 
sidebar: sidebar 
keywords: igroup 
summary: 'Sie erstellen Initiatorgruppen (igroups), um anzugeben, welche Hosts auf eine bestimmte LUN im Speichersystem zugreifen können.  Sie können SnapCenter verwenden, um eine igroup auf einem Windows-Host zu erstellen, umzubenennen, zu ändern oder zu löschen.' 
---
= Erstellen und Verwalten von igroups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie erstellen Initiatorgruppen (igroups), um anzugeben, welche Hosts auf eine bestimmte LUN im Speichersystem zugreifen können.  Sie können SnapCenter verwenden, um eine igroup auf einem Windows-Host zu erstellen, umzubenennen, zu ändern oder zu löschen.



== Erstellen einer igroup

Sie können SnapCenter verwenden, um eine igroup auf einem Windows-Host zu erstellen.  Die igroup ist im Assistenten „Datenträger erstellen“ oder „Datenträger verbinden“ verfügbar, wenn Sie die igroup einer LUN zuordnen.

*Schritte*

. Klicken Sie im linken Navigationsbereich auf *Hosts*.
. Klicken Sie auf der Seite „Hosts“ auf *Igroup*.
. Klicken Sie auf der Seite „Initiatorgruppen“ auf *Neu*.
. Definieren Sie im Dialogfeld „Igroup erstellen“ die Igroup:
+
|===
| In diesem Bereich... | Machen Sie Folgendes... 


 a| 
Speichersystem
 a| 
Wählen Sie die SVM für die LUN aus, die Sie der igroup zuordnen möchten.



 a| 
Gastgeber
 a| 
Wählen Sie den Host aus, auf dem Sie die igroup erstellen möchten.



 a| 
Igroup-Name
 a| 
Geben Sie den Namen der Igroup ein.



 a| 
Initiatoren
 a| 
Wählen Sie den Initiator aus.



 a| 
Typ
 a| 
Wählen Sie den Initiatortyp: iSCSI, FCP oder gemischt (FCP und iSCSI).

|===
. Wenn Sie mit Ihren Eingaben zufrieden sind, klicken Sie auf *OK*.
+
SnapCenter erstellt die igroup auf dem Speichersystem.





== Umbenennen einer igroup

Sie können SnapCenter verwenden, um eine vorhandene igroup umzubenennen.

*Schritte*

. Klicken Sie im linken Navigationsbereich auf *Hosts*.
. Klicken Sie auf der Seite „Hosts“ auf *Igroup*.
. Klicken Sie auf der Seite „Initiatorgruppen“ in das Feld *Storage Virtual Machine*, um eine Liste der verfügbaren SVMs anzuzeigen, und wählen Sie dann die SVM für die Igroup aus, die Sie umbenennen möchten.
. Wählen Sie in der Liste der igroups für die SVM die igroup aus, die Sie umbenennen möchten, und klicken Sie auf *Umbenennen*.
. Geben Sie im Dialogfeld „igroup umbenennen“ den neuen Namen für die igroup ein und klicken Sie auf *Umbenennen*.




== Ändern einer igroup

Sie können SnapCenter verwenden, um einer vorhandenen Igroup Igroup-Initiatoren hinzuzufügen.  Beim Erstellen einer igroup können Sie nur einen Host hinzufügen.  Wenn Sie eine Igroup für einen Cluster erstellen möchten, können Sie die Igroup ändern, um dieser Igroup weitere Knoten hinzuzufügen.

*Schritte*

. Klicken Sie im linken Navigationsbereich auf *Hosts*.
. Klicken Sie auf der Seite „Hosts“ auf *Igroup*.
. Klicken Sie auf der Seite „Initiatorgruppen“ in das Feld *Storage Virtual Machine*, um eine Dropdown-Liste der verfügbaren SVMs anzuzeigen, und wählen Sie dann die SVM für die Igroup aus, die Sie ändern möchten.
. Wählen Sie in der Liste der igroups eine igroup aus und klicken Sie auf *Initiator zu igroup hinzufügen*.
. Wählen Sie einen Host aus.
. Wählen Sie die Initiatoren aus und klicken Sie auf *OK*.




== Löschen einer igroup

Sie können SnapCenter verwenden, um eine Igroup zu löschen, wenn Sie sie nicht mehr benötigen.

*Schritte*

. Klicken Sie im linken Navigationsbereich auf *Hosts*.
. Klicken Sie auf der Seite „Hosts“ auf *Igroup*.
. Klicken Sie auf der Seite „Initiatorgruppen“ in das Feld *Storage Virtual Machine*, um eine Dropdown-Liste der verfügbaren SVMs anzuzeigen, und wählen Sie dann die SVM für die Igroup aus, die Sie löschen möchten.
. Wählen Sie in der Liste der igroups für die SVM die igroup aus, die Sie löschen möchten, und klicken Sie auf *Löschen*.
. Klicken Sie im Dialogfeld „igroup löschen“ auf *OK*.
+
SnapCenter löscht die igroup.


