---
permalink: install/concept_svm_connections_and_credentials.html 
sidebar: sidebar 
keywords: storage, connection, credentials 
summary: Bevor Sie Datenschutzvorgänge durchführen, sollten Sie die Speicherverbindungen einrichten und die Anmeldeinformationen hinzufügen, die der SnapCenter Server und die SnapCenter Plug-Ins verwenden werden. 
---
= Speicherverbindungen und Anmeldeinformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Datenschutzvorgänge durchführen, sollten Sie die Speicherverbindungen einrichten und die Anmeldeinformationen hinzufügen, die der SnapCenter Server und die SnapCenter Plug-Ins verwenden werden.



== Speicherverbindungen

Die Speicherverbindungen ermöglichen dem SnapCenter Server und den SnapCenter -Plug-Ins den Zugriff auf den ONTAP -Speicher.  Zum Einrichten dieser Verbindungen gehört auch die Konfiguration der Funktionen von AutoSupport und Event Management System (EMS).



== Anmeldeinformationen

* Domänenadministrator oder ein beliebiges Mitglied der Administratorgruppe
+
Geben Sie den Domänenadministrator oder ein beliebiges Mitglied der Administratorgruppe auf dem System an, auf dem Sie das SnapCenter Plug-In installieren. Gültige Formate für das Feld „Benutzername“ sind:

+
** _NetBIOS\Benutzername_
** _Domänen-FQDN\Benutzername_
** _Benutzername@upn_


* Lokaler Administrator (nur für Arbeitsgruppen)
+
Geben Sie für Systeme, die zu einer Arbeitsgruppe gehören, den integrierten lokalen Administrator auf dem System an, auf dem Sie das SnapCenter -Plug-In installieren. Sie können ein lokales Benutzerkonto angeben, das zur lokalen Administratorgruppe gehört, wenn das Benutzerkonto über erhöhte Berechtigungen verfügt oder die Benutzerzugriffssteuerung auf dem Hostsystem deaktiviert ist.

+
Das gültige Format für das Feld „Benutzername“ ist: _Benutzername_

* Anmeldeinformationen für einzelne Ressourcengruppen
+
Wenn Sie Anmeldeinformationen für einzelne Ressourcengruppen einrichten und der Benutzername nicht über vollständige Administratorrechte verfügt, müssen Sie dem Benutzernamen mindestens die Ressourcengruppen- und Sicherungsrechte zuweisen.


