---
permalink: install/task_configure_CA_certificate_with_snapcenter_site.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate 
summary: Sie sollten das CA-Zertifikat mit der SnapCenter -Site auf dem Windows-Host konfigurieren. 
---
= Konfigurieren des CA-Zertifikats mit der SnapCenter -Site
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten das CA-Zertifikat mit der SnapCenter -Site auf dem Windows-Host konfigurieren.

*Schritte*

. Öffnen Sie den IIS-Manager auf dem Windows-Server, auf dem SnapCenter installiert ist.
. Klicken Sie im linken Navigationsbereich auf *Verbindungen*.
. Erweitern Sie den Namen des Servers und *Sites*.
. Wählen Sie die SnapCenter -Website aus, auf der Sie das SSL-Zertifikat installieren möchten.
. Navigieren Sie zu *Aktionen* > *Site bearbeiten* und klicken Sie auf *Bindungen*.
. Wählen Sie auf der Seite „Bindungen“ die Option *Bindung für https* aus.
. Klicken Sie auf *Bearbeiten*.
. Wählen Sie aus der Dropdown-Liste „SSL-Zertifikat“ das kürzlich importierte SSL-Zertifikat aus.
. Klicken Sie auf *OK*.
+

NOTE: Die SnapCenter Scheduler-Site (Standardport: 8154, HTTPS) ist mit einem selbstsignierten Zertifikat konfiguriert.  Dieser Port kommuniziert innerhalb des SnapCenter Server-Hosts und muss nicht mit einem CA-Zertifikat konfiguriert werden.  Wenn Ihre Umgebung jedoch die Verwendung eines CA-Zertifikats erfordert, wiederholen Sie die Schritte 5 bis 9 mithilfe der SnapCenter Scheduler-Site.




NOTE: Wenn das kürzlich bereitgestellte CA-Zertifikat nicht im Dropdown-Menü aufgeführt ist, überprüfen Sie, ob das CA-Zertifikat mit dem privaten Schlüssel verknüpft ist.


IMPORTANT: Stellen Sie sicher, dass das Zertifikat über den folgenden Pfad hinzugefügt wird: *Konsolenstamm > Zertifikate – Lokaler Computer > Vertrauenswürdige Stammzertifizierungsstellen > Zertifikate*.
