---
permalink: install/task_export_ca_certificates_from_snapcenter_server.html 
sidebar: sidebar 
keywords: security,authentication, export CA certificates 
summary: Sie sollten die CA-Zertifikate vom SnapCenter -Server auf die Plug-in-Hosts exportieren. 
---
= Exportieren Sie Zertifikate der Zertifizierungsstelle (CA) vom SnapCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die CA-Zertifikate mithilfe der Microsoft Management Console (MMC) vom SnapCenter -Server auf die Plug-In-Hosts exportieren.

.Bevor Sie beginnen
Sie sollten das bidirektionale SSL konfiguriert haben.

*Schritte*

. Gehen Sie zur Microsoft-Verwaltungskonsole (MMC) und klicken Sie dann auf *Datei* > *Snap-In hinzufügen/entfernen*.
. Wählen Sie im Fenster „Snap-Ins hinzufügen oder entfernen“ *Zertifikate* aus und klicken Sie dann auf *Hinzufügen*.
. Wählen Sie im Fenster „Zertifikat-Snap-In“ die Option *Computerkonto* und klicken Sie dann auf *Fertig stellen*.
. Klicken Sie auf *Konsolenstamm* > *Zertifikate – Lokaler Computer* > *Persönlich* > *Zertifikate*.
. Klicken Sie mit der rechten Maustaste auf das beschaffte CA-Zertifikat, das für SnapCenter Server verwendet wird, und wählen Sie dann *Alle Aufgaben* > *Exportieren*, um den Exportassistenten zu starten.
. Führen Sie im Assistenten die folgenden Aktionen aus.


|===
| Für diese Option... | Gehen Sie wie folgt vor... 


 a| 
Privaten Schlüssel exportieren
 a| 
Wählen Sie *Nein, privaten Schlüssel nicht exportieren* und klicken Sie dann auf *Weiter*.



 a| 
Exportdateiformat
 a| 
Klicken Sie auf *Weiter*.



 a| 
Dateiname
 a| 
Klicken Sie auf *Durchsuchen*, geben Sie den Dateipfad zum Speichern des Zertifikats an und klicken Sie auf *Weiter*.



 a| 
Abschließen des Zertifikatexport-Assistenten
 a| 
Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig*, um den Export zu starten.

|===

NOTE: Die zertifikatsbasierte Authentifizierung wird für SnapCenter HA-Konfigurationen und das SnapCenter Plug-in for VMware vSphere nicht unterstützt.
