---
permalink: protect-scu/concept_overview_snapcenter_plug_in_for_UNIX_file_systems.html 
sidebar: sidebar 
keywords: overview, unix file system, plug-in for unix file system, backup, restore, clone 
summary: Das Plug-in für Unix-Dateisysteme unterstützt das Sichern, Wiederherstellen und Klonen von Unix-Dateisystemen. 
---
= Was Sie mit dem SnapCenter Plug-in für Unix-Dateisysteme tun können
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn das Plug-in für Unix-Dateisysteme in Ihrer Umgebung installiert ist, können Sie SnapCenter zum Sichern, Wiederherstellen und Klonen von Unix-Dateisystemen verwenden.  Sie können auch Aufgaben ausführen, die diese Vorgänge unterstützen.

* Ressourcen entdecken
* Sichern Sie Unix-Dateisysteme
* Planen von Sicherungsvorgängen
* Wiederherstellen von Dateisystemsicherungen
* Klonen von Dateisystemsicherungen
* Überwachen von Sicherungs-, Wiederherstellungs- und Klonvorgängen




== Unterstützte Konfigurationen

|===
| Artikel | Unterstützte Konfiguration 


 a| 
Umgebungen
 a| 
* Physischer Server
* Virtueller Server
+
vVol-Datenspeicher auf NFS und SAN. vVol-Datenspeicher können nur mit ONTAP Tools für VMware vSphere bereitgestellt werden.





 a| 
Betriebssysteme
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server (SLES)




 a| 
Dateisysteme
 a| 
* SAN:
+
** Sowohl LVM- als auch nicht LVM-basierte Dateisysteme
** LVM über VMDK ext3, ext4 und xfs


* NFS: NFS v3, NFS v4.x




 a| 
Protokolle
 a| 
* FC
* FCoE
* iSCSI
* NFS




 a| 
Mehrwege
 a| 
Ja

|===


== Einschränkungen

* Eine Mischung aus RDMs und virtuellen Datenträgern in einer Datenträgergruppe wird nicht unterstützt.
* Die Wiederherstellung auf Dateiebene wird nicht unterstützt.
+
Sie können jedoch eine manuelle Wiederherstellung auf Dateiebene durchführen, indem Sie die Sicherung klonen und die Dateien dann manuell kopieren.

* Eine Mischung aus Dateisystemen, die über VMDKs verteilt sind und sowohl aus NFS- als auch aus VMFS-Datenspeichern stammen, wird nicht unterstützt.
* NVMe wird nicht unterstützt.
* Bereitstellung wird nicht unterstützt.




== Features

* Ermöglicht dem Plug-in für Oracle Database, Datenschutzvorgänge auf Oracle-Datenbanken durchzuführen, indem der zugrunde liegende Host-Speicherstapel auf Linux- oder AIX-Systemen verwaltet wird
* Unterstützt Network File System (NFS)- und Storage Area Network (SAN)-Protokolle auf einem Speichersystem, auf dem ONTAP ausgeführt wird.
* Für Linux-Systeme werden Oracle-Datenbanken auf VMDK und RDM-LUNs unterstützt, wenn Sie das SnapCenter Plug-in for VMware vSphere bereitstellen und das Plug-in bei SnapCenter registrieren.
* Unterstützt Mount Guard für AIX auf SAN-Dateisystemen und LVM-Layout.
* Unterstützt Enhanced Journaled File System (JFS2) mit Inline-Protokollierung auf SAN-Dateisystemen und LVM-Layout nur für AIX-Systeme.
+
Es werden native SAN-Geräte, Dateisysteme und auf SAN-Geräten erstellte LVM-Layouts unterstützt.

* Automatisiert anwendungsorientierte Sicherungs-, Wiederherstellungs- und Klonvorgänge für UNIX-Dateisysteme in Ihrer SnapCenter -Umgebung

