---
permalink: protect-scu/reference_install_snapcenter_plug_in_for_vmware_vsphere.html 
sidebar: sidebar 
keywords: install, VMware vSphere 
summary: 'Wenn Ihre Datenbank auf virtuellen Maschinen (VMs) gespeichert ist oder Sie VMs und Datenspeicher schützen möchten, müssen Sie das SnapCenter Plug-in for VMware vSphere Appliance bereitstellen.' 
---
= Installieren Sie das SnapCenter Plug-in for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Ihre Datenbank oder Ihr Dateisystem auf virtuellen Maschinen (VMs) gespeichert ist oder Sie VMs und Datenspeicher schützen möchten, müssen Sie das SnapCenter Plug-in for VMware vSphere Appliance bereitstellen.

Informationen zur Bereitstellung finden Sie unter https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_get_started_overview.html["Bereitstellungsübersicht"^] .



== CA-Zertifikat bereitstellen

Informationen zum Konfigurieren des CA-Zertifikats mit dem SnapCenter Plug-in for VMware vSphere finden Sie unter https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_and_or_import_an_SSL_certificate_to_SnapCenter_Plug-in_for_VMware_vSphere_(SCV)["SSL-Zertifikat erstellen oder importieren"^] .



== Konfigurieren der CRL-Datei

Das SnapCenter Plug-in for VMware vSphere sucht in einem vorkonfigurierten Verzeichnis nach den CRL-Dateien.  Das Standardverzeichnis der CRL-Dateien für das SnapCenter Plug-in for VMware vSphere ist _/opt/netapp/config/crl_.

Sie können mehr als eine CRL-Datei in diesem Verzeichnis ablegen.  Die eingehenden Zertifikate werden anhand der einzelnen CRLs überprüft.
