---
permalink: protect-nsp/set_up_credentials_for_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter verwendet Anmeldeinformationen, um Benutzer für SnapCenter -Vorgänge zu authentifizieren.  Sie sollten Anmeldeinformationen für die Installation von SnapCenter -Plug-Ins und zusätzliche Anmeldeinformationen für die Durchführung von Datenschutzvorgängen auf Datenbanken oder Windows-Dateisystemen erstellen. 
---
= Einrichten von Anmeldeinformationen für von NetApp unterstützte Plug-Ins
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter verwendet Anmeldeinformationen, um Benutzer für SnapCenter -Vorgänge zu authentifizieren.  Sie sollten Anmeldeinformationen für die Installation von SnapCenter -Plug-Ins und zusätzliche Anmeldeinformationen für die Durchführung von Datenschutzvorgängen auf Datenbanken oder Windows-Dateisystemen erstellen.

.Bevor Sie beginnen
* Linux- oder AIX-Hosts
+
Sie müssen Anmeldeinformationen für die Installation von Plug-Ins auf Linux- oder AIX-Hosts einrichten.

+
Sie müssen die Anmeldeinformationen für den Root-Benutzer oder für einen Nicht-Root-Benutzer mit Sudo-Berechtigungen einrichten, um den Plug-In-Prozess zu installieren und zu starten.

+
|===


| *Best Practice:* Obwohl Sie Anmeldeinformationen für Linux erstellen dürfen, nachdem Sie Hosts bereitgestellt und Plug-Ins installiert haben, besteht die Best Practice darin, Anmeldeinformationen nach dem Hinzufügen von SVMs zu erstellen, bevor Sie Hosts bereitstellen und Plug-Ins installieren. 
|===
* Windows-Hosts
+
Sie müssen Windows-Anmeldeinformationen einrichten, bevor Sie Plug-Ins installieren.

+
Sie müssen die Anmeldeinformationen mit Administratorrechten einrichten, einschließlich Administratorrechten auf dem Remote-Host.

* Von NetApp unterstützte Plug-In-Anwendungen
+
Das Plug-In verwendet die Anmeldeinformationen, die beim Hinzufügen einer Ressource ausgewählt oder erstellt werden.  Wenn für eine Ressource während Datenschutzvorgängen keine Anmeldeinformationen erforderlich sind, können Sie die Anmeldeinformationen auf *Keine* festlegen.



.Informationen zu diesem Vorgang
Wenn Sie Anmeldeinformationen für einzelne Ressourcengruppen einrichten und der Benutzername nicht über vollständige Administratorrechte verfügt, müssen Sie dem Benutzernamen mindestens die Ressourcengruppen- und Sicherungsrechte zuweisen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite „Einstellungen“ auf *Anmeldeinformationen*.
. Klicken Sie auf *Neu*.
. Geben Sie auf der Seite *Anmeldeinformationen* die zum Konfigurieren der Anmeldeinformationen erforderlichen Informationen an:
+
|===
| Für dieses Feld... | Machen Sie Folgendes... 


 a| 
Anmeldeinformationsname
 a| 
Geben Sie einen Namen für die Anmeldeinformationen ein.



 a| 
Benutzername
 a| 
Geben Sie den Benutzernamen und das Kennwort ein, die zur Authentifizierung verwendet werden sollen.

** Domänenadministrator oder ein beliebiges Mitglied der Administratorgruppe
+
Geben Sie den Domänenadministrator oder ein beliebiges Mitglied der Administratorgruppe auf dem System an, auf dem Sie das SnapCenter Plug-In installieren. Gültige Formate für das Feld „Benutzername“ sind:

+
*** _NetBIOS\Benutzername_
*** _Domänen-FQDN\Benutzername_


** Lokaler Administrator (nur für Arbeitsgruppen)
+
Geben Sie für Systeme, die zu einer Arbeitsgruppe gehören, den integrierten lokalen Administrator auf dem System an, auf dem Sie das SnapCenter -Plug-In installieren. Sie können ein lokales Benutzerkonto angeben, das zur lokalen Administratorgruppe gehört, wenn das Benutzerkonto über erhöhte Berechtigungen verfügt oder die Benutzerzugriffssteuerung auf dem Hostsystem deaktiviert ist.  Das gültige Format für das Feld „Benutzername“ ist: _Benutzername_





 a| 
Passwort
 a| 
Geben Sie das zur Authentifizierung verwendete Passwort ein.



 a| 
Authentifizierungstyp
 a| 
Wählen Sie den Authentifizierungstyp aus, den Sie verwenden möchten.



 a| 
Verwenden Sie Sudo-Berechtigungen
 a| 
Aktivieren Sie das Kontrollkästchen *Sudo-Berechtigungen verwenden*, wenn Sie Anmeldeinformationen für einen Nicht-Root-Benutzer erstellen.


NOTE: Gilt nur für Linux- und AIX-Benutzer.

|===
. Klicken Sie auf *OK*.


Nachdem Sie die Anmeldeinformationen eingerichtet haben, möchten Sie möglicherweise die Anmeldeinformationsverwaltung einem Benutzer oder einer Benutzergruppe auf der Seite „Benutzer und Zugriff“ zuweisen.
