---
permalink: get-started/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication, untrusted domain, local workgroup, windows authentication, SQL Server authentication, Linux authentication, AIX authentication, Oracle database authentication, Oracle ASM authentication, RMAN catalog authentication 
summary: Für Anmeldeinformationen werden je nach Anwendung oder Umgebung unterschiedliche Authentifizierungsmethoden verwendet.  Anmeldeinformationen authentifizieren Benutzer, damit sie SnapCenter -Vorgänge ausführen können.  Sie sollten einen Satz Anmeldeinformationen für die Installation von Plug-Ins und einen anderen Satz für Datenschutzvorgänge erstellen. 
---
= Authentifizierungsmethoden für SnapCenter -Anmeldeinformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für Anmeldeinformationen werden je nach Anwendung oder Umgebung unterschiedliche Authentifizierungsmethoden verwendet.  Anmeldeinformationen authentifizieren Benutzer, damit sie SnapCenter -Vorgänge ausführen können.  Sie sollten einen Satz Anmeldeinformationen für die Installation von Plug-Ins und einen anderen für Datenschutzvorgänge erstellen.



== Windows-Authentifizierung

Die Windows-Authentifizierungsmethode authentifiziert sich gegenüber Active Directory.  Für die Windows-Authentifizierung wird Active Directory außerhalb von SnapCenter eingerichtet.  SnapCenter authentifiziert ohne zusätzliche Konfiguration.  Sie benötigen Windows-Anmeldeinformationen, um Hosts hinzuzufügen, Plug-In-Pakete zu installieren und Jobs zu planen.



== Nicht vertrauenswürdige Domänenauthentifizierung

SnapCenter ermöglicht Benutzern und Gruppen, die zu nicht vertrauenswürdigen Domänen gehören, das Erstellen von Windows-Anmeldeinformationen.  Damit die Authentifizierung erfolgreich ist, sollten Sie die nicht vertrauenswürdigen Domänen bei SnapCenter registrieren.



== Lokale Arbeitsgruppenauthentifizierung

SnapCenter ermöglicht die Erstellung von Windows-Anmeldeinformationen mit lokalen Arbeitsgruppenbenutzern und -gruppen.  Die Windows-Authentifizierung für lokale Arbeitsgruppenbenutzer und -gruppen erfolgt nicht während der Erstellung der Windows-Anmeldeinformationen, sondern wird verschoben, bis die Hostregistrierung und andere Hostvorgänge durchgeführt werden.



== SQL Server-Authentifizierung

Die SQL-Authentifizierungsmethode authentifiziert sich gegenüber einer SQL Server-Instanz.  Dies bedeutet, dass in SnapCenter eine SQL Server-Instanz erkannt werden muss.  Daher müssen Sie vor dem Hinzufügen von SQL-Anmeldeinformationen einen Host hinzufügen, Plug-In-Pakete installieren und Ressourcen aktualisieren.  Sie benötigen eine SQL Server-Authentifizierung, um Vorgänge wie die Planung auf SQL Server oder die Ermittlung von Ressourcen durchzuführen.



== Linux-Authentifizierung

Die Linux-Authentifizierungsmethode authentifiziert sich gegenüber einem Linux-Host.  Sie benötigen eine Linux-Authentifizierung während des ersten Schritts, bei dem Sie den Linux-Host hinzufügen und das SnapCenter Plug-Ins-Paket für Linux remote über die SnapCenter -GUI installieren.



== AIX-Authentifizierung

Die AIX-Authentifizierungsmethode authentifiziert gegenüber einem AIX-Host.  Sie benötigen eine AIX-Authentifizierung während des ersten Schritts, bei dem Sie den AIX-Host hinzufügen und das SnapCenter Plug-Ins-Paket für AIX remote über die SnapCenter -GUI installieren.



== Oracle-Datenbankauthentifizierung

Die Oracle-Datenbankauthentifizierungsmethode authentifiziert gegenüber einer Oracle-Datenbank.  Sie benötigen eine Oracle-Datenbankauthentifizierung, um Vorgänge an der Oracle-Datenbank auszuführen, wenn die Betriebssystemauthentifizierung (OS) auf dem Datenbankhost deaktiviert ist.  Bevor Sie Anmeldeinformationen für eine Oracle-Datenbank hinzufügen, sollten Sie daher einen Oracle-Benutzer mit Sysdba-Berechtigungen in der Oracle-Datenbank erstellen.



== Oracle ASM-Authentifizierung

Die Oracle ASM-Authentifizierungsmethode authentifiziert sich gegenüber einer Oracle Automatic Storage Management (ASM)-Instanz.  Die Oracle ASM-Authentifizierung ist erforderlich, wenn Sie auf eine Oracle ASM-Instanz zugreifen müssen und die Betriebssystemauthentifizierung auf dem Datenbankhost deaktiviert ist.  Erstellen Sie vor dem Hinzufügen einer Oracle ASM-Anmeldeinformation einen Oracle-Benutzer mit Systemberechtigungen in der ASM-Instanz.



== RMAN-Katalogauthentifizierung

Die RMAN-Katalogauthentifizierungsmethode authentifiziert sich gegenüber der Oracle Recovery Manager (RMAN)-Katalogdatenbank.  Wenn Sie einen externen Katalogmechanismus konfiguriert und Ihre Datenbank bei der Katalogdatenbank registriert haben, müssen Sie die RMAN-Katalogauthentifizierung hinzufügen.
