---
permalink: protect-mysql/types-of-restore-performed-for-auto-discovered-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for mysql 
summary: 'SnapCenter unterstützt Volume-basiertes SnapRestore (VBSR), Single File SnapRestore und Connect-and-Copy-Wiederherstellungstypen für automatisch erkannte MySQL-Datenbanken.' 
---
= Arten von Wiederherstellungsvorgängen für automatisch erkanntes MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SnapCenter -Plug-in für MySQL unterstützt Single File SnapRestore und Connect-and-Copy-Wiederherstellungstypen für automatisch erkannte MySQL-Datenbanken.



== Single File SnapRestore wird in NFS-Umgebungen für die folgenden Szenarien durchgeführt:

* Wenn nur die Option *Komplette Ressource* ausgewählt ist
* Wenn das ausgewählte Backup von einem SnapMirror oder SnapVault Sekundärspeicherort stammt und die Option *Complete Resource* ausgewählt ist




== Single File SnapRestore wird in SAN-Umgebungen für die folgenden Szenarien durchgeführt:

* Wenn nur die Option *Komplette Ressource* ausgewählt ist
* Wenn das Backup von einem SnapMirror oder SnapVault Sekundärspeicherort ausgewählt wird und die Option *Complete Resource* ausgewählt ist

